
2020-10-19 07:29:57,930 [17] ERROR PSLCalcu.AppRunForm - 计算引擎错误3：计算模块内部错误!
——计算错误详细信息：输入有效数据数量不足。一维偏差及得分计算要求必须有且仅有两个有效输入。。
——计算模块的名称是：106-NewMDeviationS，计算起始时间是：2020/10/15 23:00:00，计算结束时间是：2020/10/16 0:00:00。

2020-10-19 07:30:00,073 [17] ERROR PSLCalcu.AppRunForm - 计算引擎错误4：计算模块内部错误!
——计算错误详细信息：输入有效数据数量不足。一维偏差及得分计算要求必须有且仅有两个有效输入。。
——计算模块的名称是：107-NewMDeviationS，计算起始时间是：2020/10/15 23:00:00，计算结束时间是：2020/10/16 0:00:00。

2020-10-19 14:30:49,479 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMinReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:30:49,526 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMinPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:30:49,526 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquAvgReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:30:49,526 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMedianReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:30:49,526 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMedianPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:30:49,526 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMaxReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:30:49,526 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMaxPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:30:49,526 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquFarReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:30:49,526 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquStdevSReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:30:49,526 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:30:49,526 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:30:49,526 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevPNRReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:30:51,583 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:51,583 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:51,583 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:51,583 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:51,583 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:52,215 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMultiAnalogAvg的计算结果描述MANGAvg，与计算模件MMangSumAvg的计算结果描述重复，请检查！

2020-10-19 14:30:52,729 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMultiAnalogSum的计算结果描述MANGSum，与计算模件MMangSumAvg的计算结果描述重复，请检查！

2020-10-19 14:30:53,347 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:53,347 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:53,347 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:53,347 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:53,876 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:53,876 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:53,876 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:53,877 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:54,824 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模块MPVBasePlusSft的algorithmsflag参数与outputNumber参数不符！

2020-10-19 14:30:54,824 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模块MPVBasePlusSft的outputdescs参数与outputNumber参数不符！

2020-10-19 14:30:54,824 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:54,824 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:54,824 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:54,824 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:54,824 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:54,824 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:54,824 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:54,824 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:54,824 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:54,824 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:54,824 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:54,824 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:54,824 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:54,824 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:54,824 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:54,824 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,850 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,850 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,850 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,850 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,850 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,850 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBLinek，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBLineb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSumPNR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStdev，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVolatility，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeG，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGsA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,851 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,852 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,852 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,852 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,852 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,852 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,852 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,852 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,852 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,852 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,852 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,852 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,852 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLPV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBPNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQltR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStatus，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQa，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:55,853 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQc，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:30:56,725 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulSum，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 14:30:56,725 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsSum，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 14:30:56,725 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulMul，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 14:30:56,725 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsMul，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 14:30:56,725 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAvg，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 14:30:56,725 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsAvg，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 14:30:57,550 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:57,550 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:57,550 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:57,550 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:57,550 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:58,415 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:58,415 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:58,415 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:58,415 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:58,415 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:30:59,218 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaSR，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 14:30:59,218 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 14:30:59,218 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHHT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 14:30:59,218 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 14:30:59,218 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHHTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 14:30:59,218 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 14:30:59,218 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLLT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 14:30:59,219 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 14:30:59,219 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLLTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 14:31:00,935 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模块MPVBasePlusSftOri的outputdescs参数与outputNumber参数不符！

2020-10-19 14:31:00,935 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:00,935 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:00,935 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:00,935 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:00,935 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:00,935 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:00,935 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:00,935 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:00,935 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:00,935 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:00,935 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:00,935 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:00,935 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:00,935 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:00,935 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:06,698 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMinReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:31:06,698 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMinPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:31:06,698 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquAvgReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:31:06,698 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMedianReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:31:06,698 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMedianPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:31:06,698 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMaxReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:31:06,698 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMaxPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:31:06,698 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquFarReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:31:06,698 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquStdevSReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:31:06,698 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:31:06,698 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:31:06,698 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevPNRReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 14:31:08,072 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:08,072 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:08,072 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:08,073 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:08,073 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:08,736 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMultiAnalogAvg的计算结果描述MANGAvg，与计算模件MMangSumAvg的计算结果描述重复，请检查！

2020-10-19 14:31:09,547 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMultiAnalogSum的计算结果描述MANGSum，与计算模件MMangSumAvg的计算结果描述重复，请检查！

2020-10-19 14:31:10,299 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:10,299 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:10,299 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:10,299 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:10,859 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:10,859 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:10,859 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:10,859 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:11,549 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模块MPVBasePlusSft的algorithmsflag参数与outputNumber参数不符！

2020-10-19 14:31:11,549 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模块MPVBasePlusSft的outputdescs参数与outputNumber参数不符！

2020-10-19 14:31:11,549 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:11,549 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:11,549 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:11,549 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:11,549 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:11,549 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:11,549 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:11,549 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:11,549 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:11,549 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:11,550 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:11,550 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:11,550 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:11,550 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:11,550 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:11,550 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBLinek，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBLineb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSumPNR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStdev，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVolatility，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeG，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGsA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,032 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLPV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,033 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,034 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,034 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,034 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,034 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,034 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,034 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,034 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBPNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,034 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQltR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,034 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStatus，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,034 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQa，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,034 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:18,034 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQc，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:31:29,090 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulSum，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 14:31:29,091 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsSum，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 14:31:29,091 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulMul，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 14:31:29,091 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsMul，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 14:31:29,091 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAvg，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 14:31:29,091 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsAvg，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 14:31:29,741 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:29,741 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:29,741 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:29,741 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:29,741 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:30,949 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:30,949 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:30,949 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:30,949 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:31:30,949 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 14:36:41,792 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaSR，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 14:36:41,792 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 14:36:41,792 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHHT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 14:36:41,792 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 14:36:41,792 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHHTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 14:36:41,792 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 14:36:41,792 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLLT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 14:36:41,792 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 14:36:41,792 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLLTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 14:36:42,550 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模块MPVBasePlusSftOri的outputdescs参数与outputNumber参数不符！

2020-10-19 14:36:42,551 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:36:42,551 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:36:42,551 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:36:42,551 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:36:42,551 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:36:42,551 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:36:42,551 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:36:42,551 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:36:42,551 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:36:42,551 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:36:42,551 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:36:42,551 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:36:42,551 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:36:42,551 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 14:36:42,552 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:24:51,390 [9] ERROR PSLCalcu.PSLCalcuConfigDAO - DAO层PSLCalcuConfigDAO.ReadConfig()错误：---------->

2020-10-19 15:24:51,390 [9] ERROR PSLCalcu.PSLCalcuConfigDAO - sql语句：use psldb;select pslcalcuconfig.fid,pslcalcuconfig.sourcetagname,pslcalcuconfig.sourcetagdb,pslcalcuconfig.sourcetagdesc,pslcalcuconfig.sourcetagdim,pslcalcuconfig.sourcetagmrb,pslcalcuconfig.sourcetagmre,pslcalcuconfig.fmodulename,pslcalcuconfig.fnode,pslcalcuconfig.fgroup,pslcalcuconfig.forder,pslcalcuconfig.falgorithmsflag,pslcalcuconfig.fparas,pslcalcuconfig.fcondpslnames,pslcalcuconfig.fcondexpression,pslcalcuconfig.foutputtable,pslcalcuconfig.foutputnumber,pslcalcuconfig.foutputpsltagnames,pslcalcuconfig.finterval,pslcalcuconfig.fintervaltype,pslcalcuconfig.fdelay,pslcalcuconfig.fstarttime from pslcalcuconfig ORDER BY `fid` ASC

2020-10-19 15:24:51,414 [9] ERROR PSLCalcu.PSLCalcuConfigDAO - 错误信息：System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at PSLCalcu.PSLCalcuConfigDAO.ReadConfig() in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu\DAO\PSLCalcuConfigDAO.cs:line 349

2020-10-19 15:25:14,628 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMinReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:25:14,628 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMinPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:25:14,628 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquAvgReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:25:14,628 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMedianReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:25:14,628 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMedianPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:25:14,628 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMaxReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:25:14,628 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMaxPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:25:14,628 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquFarReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:25:14,628 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquStdevSReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:25:14,628 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:25:14,628 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:25:14,628 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevPNRReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:25:15,951 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:15,951 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:15,951 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:15,951 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:15,951 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:16,470 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMultiAnalogAvg的计算结果描述MANGAvg，与计算模件MMangSumAvg的计算结果描述重复，请检查！

2020-10-19 15:25:16,895 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMultiAnalogSum的计算结果描述MANGSum，与计算模件MMangSumAvg的计算结果描述重复，请检查！

2020-10-19 15:25:17,344 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:17,344 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:17,344 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:17,344 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:17,765 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:17,765 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:17,765 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:17,765 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:18,371 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模块MPVBasePlusSft的algorithmsflag参数与outputNumber参数不符！

2020-10-19 15:25:18,371 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模块MPVBasePlusSft的outputdescs参数与outputNumber参数不符！

2020-10-19 15:25:18,371 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,371 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,371 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,371 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,371 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,371 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,371 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,372 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,372 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,372 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,372 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,372 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,372 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,372 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,372 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,372 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,668 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,668 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,668 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,668 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,668 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,668 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,668 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,668 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,669 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBLinek，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,669 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBLineb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,669 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSumPNR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,669 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,669 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStdev，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,669 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVolatility，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,669 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,669 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,669 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,669 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeG，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,669 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,669 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,669 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGsA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,669 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,669 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,669 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,669 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,670 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,670 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,670 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,670 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,670 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,670 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,670 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,670 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,670 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,670 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,670 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,670 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,670 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,670 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,670 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,670 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,670 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,670 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLPV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBPNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQltR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStatus，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQa，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:18,671 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQc，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:19,467 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulSum，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:25:19,467 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsSum，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:25:19,467 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulMul，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:25:19,467 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsMul，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:25:19,467 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAvg，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:25:19,467 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsAvg，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:25:20,036 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:20,036 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:20,036 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:20,036 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:20,036 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:20,610 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:20,610 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:20,610 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:20,611 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:20,611 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:25:21,231 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaSR，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:25:21,231 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:25:21,231 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHHT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:25:21,231 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:25:21,231 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHHTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:25:21,231 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:25:21,231 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLLT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:25:21,231 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:25:21,231 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLLTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:25:21,784 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模块MPVBasePlusSftOri的outputdescs参数与outputNumber参数不符！

2020-10-19 15:25:21,785 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:21,785 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:21,785 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:21,785 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:21,785 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:21,785 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:21,785 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:21,785 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:21,785 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:21,785 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:21,785 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:21,785 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:21,785 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:21,785 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:21,785 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:25:21,785 [9] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:47,345 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMinReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:26:47,345 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMinPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:26:47,345 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquAvgReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:26:47,345 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMedianReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:26:47,345 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMedianPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:26:47,345 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMaxReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:26:47,345 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMaxPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:26:47,345 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquFarReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:26:47,345 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquStdevSReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:26:47,345 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:26:47,345 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:26:47,345 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevPNRReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:26:49,173 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:49,173 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:49,173 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:49,173 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:49,173 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:49,769 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMultiAnalogAvg的计算结果描述MANGAvg，与计算模件MMangSumAvg的计算结果描述重复，请检查！

2020-10-19 15:26:50,183 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMultiAnalogSum的计算结果描述MANGSum，与计算模件MMangSumAvg的计算结果描述重复，请检查！

2020-10-19 15:26:50,754 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:50,754 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:50,754 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:50,754 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:51,006 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:51,006 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:51,006 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:51,006 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:51,401 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模块MPVBasePlusSft的algorithmsflag参数与outputNumber参数不符！

2020-10-19 15:26:51,401 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模块MPVBasePlusSft的outputdescs参数与outputNumber参数不符！

2020-10-19 15:26:51,401 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,401 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,401 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,401 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,401 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,401 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,401 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,401 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,402 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,402 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,402 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,402 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,402 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,402 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,402 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,402 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,452 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,452 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,452 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,452 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,452 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,452 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,452 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,452 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBLinek，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBLineb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSumPNR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStdev，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVolatility，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeG，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGsA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,453 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLPV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,454 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,455 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,455 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,455 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,455 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBPNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,455 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQltR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,455 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStatus，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,455 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQa，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,455 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:51,455 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQc，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:52,065 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulSum，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:26:52,065 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsSum，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:26:52,065 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulMul，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:26:52,065 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsMul，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:26:52,065 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAvg，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:26:52,065 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsAvg，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:26:52,554 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:52,554 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:52,554 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:52,554 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:52,554 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:53,009 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:53,009 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:53,009 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:53,009 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:53,009 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:26:53,521 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaSR，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:26:53,521 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:26:53,521 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHHT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:26:53,521 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:26:53,521 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHHTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:26:53,521 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:26:53,521 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLLT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:26:53,521 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:26:53,521 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLLTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:26:54,042 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:54,042 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:54,042 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:54,042 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:54,042 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:54,042 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:54,042 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:54,042 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:54,042 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:54,042 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:54,042 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:54,042 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:54,043 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:54,043 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:54,043 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:26:54,043 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:26,871 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMinReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:30:26,871 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMinPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:30:26,871 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquAvgReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:30:26,871 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMedianReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:30:26,871 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMedianPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:30:26,871 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMaxReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:30:26,871 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMaxPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:30:26,871 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquFarReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:30:26,871 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquStdevSReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:30:26,871 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:30:26,871 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:30:26,871 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevPNRReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:30:28,138 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:28,138 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:28,138 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:28,138 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:28,138 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:28,616 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMultiAnalogAvg的计算结果描述MANGAvg，与计算模件MMangSumAvg的计算结果描述重复，请检查！

2020-10-19 15:30:29,009 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMultiAnalogSum的计算结果描述MANGSum，与计算模件MMangSumAvg的计算结果描述重复，请检查！

2020-10-19 15:30:29,422 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:29,422 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:29,422 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:29,422 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:29,829 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:29,830 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:29,830 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:29,830 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:30,497 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,497 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,497 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,497 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,497 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,497 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,497 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,497 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,497 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,497 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,497 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,497 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,497 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,497 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,497 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,497 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,673 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,673 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,673 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,673 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,673 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,673 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,673 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,673 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,673 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBLinek，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,673 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBLineb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,673 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSumPNR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,673 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,673 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStdev，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,673 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVolatility，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,673 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeG，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGsA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,674 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLPV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBPNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQltR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStatus，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,675 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQa，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,676 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:30,676 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQc，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:31,339 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulSum，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:30:31,339 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsSum，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:30:31,339 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulMul，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:30:31,339 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsMul，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:30:31,339 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAvg，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:30:31,339 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsAvg，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:30:31,897 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:31,897 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:31,897 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:31,897 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:31,897 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:32,529 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:32,529 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:32,529 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:32,529 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:32,529 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:30:33,210 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaSR，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:30:33,211 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:30:33,211 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHHT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:30:33,211 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:30:33,211 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHHTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:30:33,211 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:30:33,211 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLLT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:30:33,211 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:30:33,211 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLLTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:30:33,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:33,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:33,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:33,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:33,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:33,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:33,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:33,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:33,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:33,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:33,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:33,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:33,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:33,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:33,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:30:33,854 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:31:34,532 [15] ERROR PSLCalcu.ConfigCSV - 概化计算组态文件组态信息错误。算法参数格式有误。请检查组态文件！
****算法配置有问题的数据行是(总表Excel行数)：1。

2020-10-19 15:40:41,350 [15] ERROR PSLCalcu.ConfigCSV - 概化计算组态文件组态信息错误。算法参数格式有误。请检查组态文件！
****算法配置有问题的数据行是(总表Excel行数)：1。

2020-10-19 15:42:13,694 [12] ERROR PSLCalcu.ConfigCSV - 概化计算组态文件组态信息错误。算法参数格式有误。请检查组态文件！
****算法配置有问题的数据行是(总表Excel行数)：1。

2020-10-19 15:44:02,822 [14] ERROR PSLCalcu.ConfigCSV - 概化计算组态文件组态信息错误。算法参数格式有误。请检查组态文件！
****算法配置有问题的数据行是(总表Excel行数)：1。

2020-10-19 15:44:27,135 [14] ERROR PSLCalcu.ConfigCSV - 概化计算组态文件组态信息错误。算法参数格式有误。请检查组态文件！
****算法配置有问题的数据行是(总表Excel行数)：1。

2020-10-19 15:45:41,752 [14] ERROR PSLCalcu.ConfigCSV - 概化计算组态文件组态信息错误。算法参数格式有误。请检查组态文件！
****算法配置有问题的数据行是(总表Excel行数)：1。

2020-10-19 15:49:00,919 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMinReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:49:00,919 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMinPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:49:00,919 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquAvgReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:49:00,919 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMedianReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:49:00,919 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMedianPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:49:00,919 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMaxReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:49:00,919 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMaxPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:49:00,919 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquFarReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:49:00,919 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquStdevSReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:49:00,919 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:49:00,919 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:49:00,919 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevPNRReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 15:49:02,074 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:02,074 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:02,074 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:02,074 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:02,074 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:02,720 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMultiAnalogAvg的计算结果描述MANGAvg，与计算模件MMangSumAvg的计算结果描述重复，请检查！

2020-10-19 15:49:03,224 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMultiAnalogSum的计算结果描述MANGSum，与计算模件MMangSumAvg的计算结果描述重复，请检查！

2020-10-19 15:49:03,779 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:03,779 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:03,780 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:03,780 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:04,305 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:04,305 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:04,305 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:04,305 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:05,052 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,052 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,052 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,052 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,052 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,052 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,052 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,052 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,052 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,052 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,052 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,052 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,052 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,052 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,052 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,052 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,214 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,214 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,214 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,214 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,214 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,214 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,214 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,214 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,214 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,215 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,215 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,215 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,215 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,215 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,215 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,215 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,849 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,849 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,849 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,850 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,850 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,850 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,850 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,850 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,850 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBLinek，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,850 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBLineb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,850 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSumPNR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,850 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,850 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStdev，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,850 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVolatility，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,850 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,850 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,850 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,850 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeG，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,850 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,851 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,851 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGsA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,851 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,851 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,851 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,851 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,851 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,851 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,851 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,851 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,851 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,851 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,851 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,851 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,851 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,852 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,852 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,853 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,854 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,854 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,854 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,854 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLPV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,854 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,854 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,854 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,854 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,854 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,854 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,854 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,854 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,854 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,854 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,855 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBPNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,855 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQltR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,855 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStatus，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,855 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQa，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,855 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:05,855 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQc，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 15:49:06,480 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulSum，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:49:06,480 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsSum，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:49:06,480 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulMul，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:49:06,480 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsMul，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:49:06,480 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAvg，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:49:06,480 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsAvg，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 15:49:07,045 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:07,045 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:07,045 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:07,045 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:07,045 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:07,574 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:07,574 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:07,574 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:07,574 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:07,574 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 15:49:08,146 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaSR，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:49:08,146 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:49:08,146 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHHT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:49:08,146 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:49:08,147 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHHTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:49:08,147 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:49:08,147 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLLT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:49:08,147 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 15:49:08,147 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLLTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 17:15:36,700 [24] ERROR PSLCalcu.PSLHistoryCalcuConfigDAO - DAO层PSLDataDAO.Read()错误：---------->
sql语句：use psldb;select tagid,tagstarttime,tagendtime,tagvalue,tagstatus from psldata202001 where tagid='1102' and tagstarttime between '637134336000000000' and '637134336600000000'
错误信息：MySql.Data.MySqlClient.MySqlException (0x80004005): Invalid attempt to Read when reader is closed.
   at MySql.Data.MySqlClient.MySqlDataReader.Read()
   at PSLCalcu.PSLDataDAO.IDataReader2PSLDataItems(IDataReader reader) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu\DAO\PSLDataDAO.cs:line 1179
   at PSLCalcu.PSLDataDAO.Read(UInt32 tagid, DateTime startdate, DateTime enddate) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu\DAO\PSLDataDAO.cs:line 566

2020-10-19 21:23:34,118 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMinReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:23:34,118 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMinPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:23:34,118 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquAvgReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:23:34,118 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMedianReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:23:34,118 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMedianPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:23:34,118 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMaxReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:23:34,118 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMaxPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:23:34,118 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquFarReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:23:34,118 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquStdevSReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:23:34,118 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:23:34,118 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:23:34,118 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevPNRReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:23:35,611 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:35,611 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:35,611 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:35,611 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:35,611 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:36,266 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMultiAnalogAvg的计算结果描述MANGAvg，与计算模件MMangSumAvg的计算结果描述重复，请检查！

2020-10-19 21:23:36,674 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMultiAnalogSum的计算结果描述MANGSum，与计算模件MMangSumAvg的计算结果描述重复，请检查！

2020-10-19 21:23:37,240 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:37,241 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:37,241 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:37,241 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:37,794 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:37,794 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:37,794 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:37,794 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:38,602 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:38,602 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:38,602 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:38,602 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:38,602 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:38,602 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:38,603 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:38,603 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:38,603 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:38,603 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:38,603 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:38,603 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:38,603 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:38,603 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:38,603 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:38,603 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,166 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,166 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,166 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,166 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,167 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,167 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,167 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,167 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,167 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,167 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,167 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,167 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,167 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,167 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,167 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,167 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBLinek，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBLineb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSumPNR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStdev，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVolatility，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeG，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGsA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,710 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLPV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBPNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQltR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStatus，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQa，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:39,711 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQc，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:23:40,288 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulSum，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 21:23:40,288 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsSum，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 21:23:40,288 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulMul，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 21:23:40,288 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsMul，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 21:23:40,288 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAvg，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 21:23:40,288 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsAvg，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 21:23:40,909 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:40,909 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:40,909 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:40,909 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:40,909 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:41,546 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:41,546 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:41,546 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:41,546 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:41,546 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:23:42,187 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaSR，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 21:23:42,187 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 21:23:42,187 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHHT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 21:23:42,187 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 21:23:42,187 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHHTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 21:23:42,187 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 21:23:42,188 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLLT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 21:23:42,188 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 21:23:42,188 [11] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLLTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 21:31:16,586 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMinReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:31:16,587 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMinPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:31:16,587 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquAvgReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:31:16,587 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMedianReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:31:16,587 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMedianPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:31:16,587 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMaxReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:31:16,587 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquMaxPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:31:16,587 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquFarReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:31:16,587 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquStdevSReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:31:16,587 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:31:16,587 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevPNReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:31:16,587 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAEquRTD_OLD的计算结果描述EquDevPNRReal，与计算模件MMTAEquRTD的计算结果描述重复，请检查！

2020-10-19 21:31:18,152 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:18,152 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:18,152 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:18,152 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:18,152 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:18,652 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMultiAnalogAvg的计算结果描述MANGAvg，与计算模件MMangSumAvg的计算结果描述重复，请检查！

2020-10-19 21:31:19,084 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMultiAnalogSum的计算结果描述MANGSum，与计算模件MMangSumAvg的计算结果描述重复，请检查！

2020-10-19 21:31:19,542 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:19,542 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:19,542 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:19,542 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviation2DSpan的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:19,984 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:19,984 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:19,984 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:19,984 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MDeviationSpan的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:20,644 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:20,644 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:20,644 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:20,644 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:20,644 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:20,644 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:20,644 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:20,644 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:20,644 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:20,644 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:20,644 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:20,644 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:20,644 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:20,644 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:20,645 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:20,645 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSft的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,287 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,287 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,287 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,287 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,287 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,287 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,287 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,288 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,288 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,288 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,288 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,288 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,288 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,288 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,288 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,288 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBasePlusSftOri的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,833 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,833 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMinTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,833 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,833 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,833 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,833 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,833 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,833 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSumkb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,833 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBLinek，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,833 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBLineb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,833 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSumPNR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBAbsSum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStdev，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVolatility，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTime，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeG，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGsA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxTimeGvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBSDMaxR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN1Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN2Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDN3Num，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBTNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVMax，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVMin，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBVAvg，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,834 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvC，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvA，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTsV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTeV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTvT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSLPV，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStbTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBNoStbTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBUpTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSLT，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,835 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSLTEnd，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,836 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBDownTSL，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,836 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBPNum，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,836 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQltR，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,836 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBStatus，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,836 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQa，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,836 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQb，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:21,836 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MPVBaseShort的计算结果描述PVBQc，与计算模件MPVBaseLong的计算结果描述重复，请检查！

2020-10-19 21:31:22,418 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulSum，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 21:31:22,418 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsSum，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 21:31:22,418 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulMul，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 21:31:22,418 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsMul，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 21:31:22,418 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAvg，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 21:31:22,418 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMAddMul的计算结果描述AddMulAbsAvg，与计算模件MAddMul的计算结果描述重复，请检查！

2020-10-19 21:31:22,973 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:22,973 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:22,973 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:22,973 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:22,973 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviation2DS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:23,555 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevSP，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:23,555 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevErr，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:23,555 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevErrR，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:23,555 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevScore，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:23,555 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件NewMDeviationS的计算结果描述DevScoreA，与计算模件MDeviation2DS的计算结果描述重复，请检查！

2020-10-19 21:31:24,118 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaSR，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 21:31:24,118 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 21:31:24,118 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHHT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 21:31:24,118 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 21:31:24,118 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaHHTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 21:31:24,118 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 21:31:24,118 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLLT，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 21:31:24,118 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 21:31:24,118 [10] ERROR PSLCalcu.PSLModulesDAO - 计算模件MMTAAnaDevOR的计算结果描述TEvaLLTF，与计算模件MMTATEva的计算结果描述重复，请检查！

2020-10-19 21:31:45,130 [7] ERROR PSLCalcu.PSLTagNameIdMapDAO - 第1行的源标签010100MAINSTMP_FOPC2WAVG_1MIN，在计算结果标签（已在库中的标签和要导入的配置表标签）中不存在，请检查！
