
2020-10-13 20:30:33,777 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/30 6:00:00，计算结束时间是：2020/1/30 7:00:00。

2020-10-13 20:30:34,114 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误2：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 3:00:00，计算结束时间是：2020/1/30 4:00:00。

2020-10-13 20:30:34,416 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误3：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 0:00:00，计算结束时间是：2020/1/1 1:00:00。

2020-10-13 20:30:34,518 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误4：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 0:00:00，计算结束时间是：2020/1/1 1:00:00。

2020-10-13 20:30:35,245 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误5：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/30 7:00:00，计算结束时间是：2020/1/30 8:00:00。

2020-10-13 20:30:35,381 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误6：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 4:00:00，计算结束时间是：2020/1/30 5:00:00。

2020-10-13 20:30:35,481 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误7：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 1:00:00，计算结束时间是：2020/1/1 2:00:00。

2020-10-13 20:30:35,568 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误8：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 1:00:00，计算结束时间是：2020/1/1 2:00:00。

2020-10-13 20:30:36,042 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误9：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/30 8:00:00，计算结束时间是：2020/1/30 9:00:00。

2020-10-13 20:30:36,163 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误10：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 5:00:00，计算结束时间是：2020/1/30 6:00:00。

2020-10-13 20:30:36,242 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误11：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 2:00:00，计算结束时间是：2020/1/1 3:00:00。

2020-10-13 20:30:36,335 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误12：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 2:00:00，计算结束时间是：2020/1/1 3:00:00。

2020-10-13 20:30:36,884 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误13：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/30 9:00:00，计算结束时间是：2020/1/30 10:00:00。

2020-10-13 20:30:37,086 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误14：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 6:00:00，计算结束时间是：2020/1/30 7:00:00。

2020-10-13 20:30:37,192 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误15：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 3:00:00，计算结束时间是：2020/1/1 4:00:00。

2020-10-13 20:30:37,279 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误16：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 3:00:00，计算结束时间是：2020/1/1 4:00:00。

2020-10-13 20:30:37,802 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误17：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/30 10:00:00，计算结束时间是：2020/1/30 11:00:00。

2020-10-13 20:30:38,587 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误18：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 7:00:00，计算结束时间是：2020/1/30 8:00:00。

2020-10-13 20:30:38,764 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误19：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 4:00:00，计算结束时间是：2020/1/1 5:00:00。

2020-10-13 20:30:38,869 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误20：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 4:00:00，计算结束时间是：2020/1/1 5:00:00。

2020-10-13 20:30:39,984 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误21：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/30 11:00:00，计算结束时间是：2020/1/30 12:00:00。

2020-10-13 20:30:40,614 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误22：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 8:00:00，计算结束时间是：2020/1/30 9:00:00。

2020-10-13 20:30:40,743 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误23：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 5:00:00，计算结束时间是：2020/1/1 6:00:00。

2020-10-13 20:30:40,862 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误24：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 5:00:00，计算结束时间是：2020/1/1 6:00:00。

2020-10-13 20:30:41,743 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误25：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/30 12:00:00，计算结束时间是：2020/1/30 13:00:00。

2020-10-13 20:30:42,600 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误26：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 9:00:00，计算结束时间是：2020/1/30 10:00:00。

2020-10-13 20:30:42,677 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误27：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 6:00:00，计算结束时间是：2020/1/1 7:00:00。

2020-10-13 20:30:42,772 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误28：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 6:00:00，计算结束时间是：2020/1/1 7:00:00。

2020-10-13 20:30:43,446 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误29：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/30 13:00:00，计算结束时间是：2020/1/30 14:00:00。

2020-10-13 20:30:43,608 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误30：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 10:00:00，计算结束时间是：2020/1/30 11:00:00。

2020-10-13 20:30:43,704 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误31：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 7:00:00，计算结束时间是：2020/1/1 8:00:00。

2020-10-13 20:30:43,796 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误32：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 7:00:00，计算结束时间是：2020/1/1 8:00:00。

2020-10-13 20:30:44,487 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误33：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/30 14:00:00，计算结束时间是：2020/1/30 15:00:00。

2020-10-13 20:30:44,620 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误34：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 11:00:00，计算结束时间是：2020/1/30 12:00:00。

2020-10-13 20:30:44,699 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误35：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 8:00:00，计算结束时间是：2020/1/1 9:00:00。

2020-10-13 20:30:44,810 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误36：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 8:00:00，计算结束时间是：2020/1/1 9:00:00。

2020-10-13 20:30:45,510 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误37：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/30 15:00:00，计算结束时间是：2020/1/30 16:00:00。

2020-10-13 20:30:45,618 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误38：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 12:00:00，计算结束时间是：2020/1/30 13:00:00。

2020-10-13 20:30:45,726 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误39：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 9:00:00，计算结束时间是：2020/1/1 10:00:00。

2020-10-13 20:30:45,816 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误40：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 9:00:00，计算结束时间是：2020/1/1 10:00:00。

2020-10-13 20:30:46,647 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误41：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/30 16:00:00，计算结束时间是：2020/1/30 17:00:00。

2020-10-13 20:30:46,782 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误42：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 13:00:00，计算结束时间是：2020/1/30 14:00:00。

2020-10-13 20:30:46,860 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误43：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 10:00:00，计算结束时间是：2020/1/1 11:00:00。

2020-10-13 20:30:46,973 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误44：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 10:00:00，计算结束时间是：2020/1/1 11:00:00。

2020-10-13 20:30:47,603 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误45：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/30 17:00:00，计算结束时间是：2020/1/30 18:00:00。

2020-10-13 20:30:47,731 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误46：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 14:00:00，计算结束时间是：2020/1/30 15:00:00。

2020-10-13 20:30:47,870 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误47：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 11:00:00，计算结束时间是：2020/1/1 12:00:00。

2020-10-13 20:30:47,957 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误48：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 11:00:00，计算结束时间是：2020/1/1 12:00:00。

2020-10-13 20:30:48,718 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误49：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/30 18:00:00，计算结束时间是：2020/1/30 19:00:00。

2020-10-13 20:30:48,823 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误50：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 15:00:00，计算结束时间是：2020/1/30 16:00:00。

2020-10-13 20:30:48,945 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误51：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 12:00:00，计算结束时间是：2020/1/1 13:00:00。

2020-10-13 20:30:49,026 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误52：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 12:00:00，计算结束时间是：2020/1/1 13:00:00。

2020-10-13 20:30:49,720 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误53：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/30 19:00:00，计算结束时间是：2020/1/30 20:00:00。

2020-10-13 20:30:49,904 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误54：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 16:00:00，计算结束时间是：2020/1/30 17:00:00。

2020-10-13 20:30:50,019 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误55：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 13:00:00，计算结束时间是：2020/1/1 14:00:00。

2020-10-13 20:30:50,107 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误56：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 13:00:00，计算结束时间是：2020/1/1 14:00:00。

2020-10-13 20:30:50,496 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误57：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/30 20:00:00，计算结束时间是：2020/1/30 21:00:00。

2020-10-13 20:30:50,623 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误58：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 17:00:00，计算结束时间是：2020/1/30 18:00:00。

2020-10-13 20:30:50,732 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误59：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 14:00:00，计算结束时间是：2020/1/1 15:00:00。

2020-10-13 20:30:50,828 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误60：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 14:00:00，计算结束时间是：2020/1/1 15:00:00。

2020-10-13 20:30:51,628 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误61：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/30 21:00:00，计算结束时间是：2020/1/30 22:00:00。

2020-10-13 20:30:51,780 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误62：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 18:00:00，计算结束时间是：2020/1/30 19:00:00。

2020-10-13 20:30:51,872 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误63：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 15:00:00，计算结束时间是：2020/1/1 16:00:00。

2020-10-13 20:30:51,970 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误64：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 15:00:00，计算结束时间是：2020/1/1 16:00:00。

2020-10-13 20:30:52,836 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误65：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/30 22:00:00，计算结束时间是：2020/1/30 23:00:00。

2020-10-13 20:30:52,945 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误66：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 19:00:00，计算结束时间是：2020/1/30 20:00:00。

2020-10-13 20:30:53,043 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误67：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 16:00:00，计算结束时间是：2020/1/1 17:00:00。

2020-10-13 20:30:53,140 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误68：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 16:00:00，计算结束时间是：2020/1/1 17:00:00。

2020-10-13 20:30:53,930 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误69：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/30 23:00:00，计算结束时间是：2020/1/31 0:00:00。

2020-10-13 20:30:54,268 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误70：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 20:00:00，计算结束时间是：2020/1/30 21:00:00。

2020-10-13 20:30:54,392 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误71：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 17:00:00，计算结束时间是：2020/1/1 18:00:00。

2020-10-13 20:30:54,496 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误72：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 17:00:00，计算结束时间是：2020/1/1 18:00:00。

2020-10-13 20:30:54,760 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误73：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 0:00:00，计算结束时间是：2020/1/31 1:00:00。

2020-10-13 20:30:54,913 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误74：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 21:00:00，计算结束时间是：2020/1/30 22:00:00。

2020-10-13 20:30:54,984 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误75：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 18:00:00，计算结束时间是：2020/1/1 19:00:00。

2020-10-13 20:30:55,090 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误76：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 18:00:00，计算结束时间是：2020/1/1 19:00:00。

2020-10-13 20:30:55,174 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误77：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 1:00:00，计算结束时间是：2020/1/31 2:00:00。

2020-10-13 20:30:55,302 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误78：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 22:00:00，计算结束时间是：2020/1/30 23:00:00。

2020-10-13 20:30:55,386 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误79：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 19:00:00，计算结束时间是：2020/1/1 20:00:00。

2020-10-13 20:30:55,497 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误80：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 19:00:00，计算结束时间是：2020/1/1 20:00:00。

2020-10-13 20:30:55,655 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误81：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 2:00:00，计算结束时间是：2020/1/31 3:00:00。

2020-10-13 20:30:55,796 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误82：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/30 23:00:00，计算结束时间是：2020/1/31 0:00:00。

2020-10-13 20:30:55,913 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误83：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 20:00:00，计算结束时间是：2020/1/1 21:00:00。

2020-10-13 20:30:56,039 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误84：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 20:00:00，计算结束时间是：2020/1/1 21:00:00。

2020-10-13 20:30:56,318 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误85：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 3:00:00，计算结束时间是：2020/1/31 4:00:00。

2020-10-13 20:30:56,490 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误86：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 0:00:00，计算结束时间是：2020/1/31 1:00:00。

2020-10-13 20:30:56,622 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误87：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 21:00:00，计算结束时间是：2020/1/1 22:00:00。

2020-10-13 20:30:56,721 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误88：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 21:00:00，计算结束时间是：2020/1/1 22:00:00。

2020-10-13 20:30:59,254 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误89：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 4:00:00，计算结束时间是：2020/1/31 5:00:00。

2020-10-13 20:30:59,381 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误90：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 1:00:00，计算结束时间是：2020/1/31 2:00:00。

2020-10-13 20:31:39,851 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误91：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 22:00:00，计算结束时间是：2020/1/1 23:00:00。

2020-10-13 20:33:37,601 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误92：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 22:00:00，计算结束时间是：2020/1/1 23:00:00。

2020-10-13 20:33:38,426 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误93：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 5:00:00，计算结束时间是：2020/1/31 6:00:00。

2020-10-13 20:33:38,690 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误94：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 2:00:00，计算结束时间是：2020/1/31 3:00:00。

2020-10-13 20:33:43,024 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误95：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：102-MDevLimitShort，计算起始时间是：2020/1/1 23:00:00，计算结束时间是：2020/1/2 0:00:00。

2020-10-13 20:34:02,568 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误96：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at PSLCalcu.Module.DAL.AlgorithmDAL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\DAL\AlgorithmDAL.cs:line 459
   at PSLCalcu.Module.BLL.AlgorithmBLL.insertMDevLimit(MDevLimitMessageOutBadClass newClass, String type, String year, String month, String day, String hour) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\BLL\AlgorithmBLL.cs:line 308
   at PSLCalcu.Module.MDevLimitShort.Calcu(List`1[] inputs, CalcuInfo calcuinfo) in D:\C# Project\JSYXX\PSLCalcu_Test\PSLCalcu.Module\New_Base_Caculate\MDevLimitShort.cs:line 512。
——计算模块的名称是：103-MDevLimitShort，计算起始时间是：2020/1/1 23:00:00，计算结束时间是：2020/1/2 0:00:00。

2020-10-13 20:35:30,757 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误97：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 6:00:00，计算结束时间是：2020/1/31 7:00:00。

2020-10-13 20:35:30,872 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误98：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 3:00:00，计算结束时间是：2020/1/31 4:00:00。

2020-10-13 20:42:57,351 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 7:00:00，计算结束时间是：2020/1/31 8:00:00。

2020-10-13 20:42:57,509 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误2：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 4:00:00，计算结束时间是：2020/1/31 5:00:00。

2020-10-13 20:43:17,563 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误3：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 8:00:00，计算结束时间是：2020/1/31 9:00:00。

2020-10-13 20:43:17,741 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误4：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 5:00:00，计算结束时间是：2020/1/31 6:00:00。

2020-10-13 20:43:18,609 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误5：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 9:00:00，计算结束时间是：2020/1/31 10:00:00。

2020-10-13 20:43:18,721 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误6：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 6:00:00，计算结束时间是：2020/1/31 7:00:00。

2020-10-13 20:43:19,808 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误7：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 10:00:00，计算结束时间是：2020/1/31 11:00:00。

2020-10-13 20:43:19,921 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误8：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 7:00:00，计算结束时间是：2020/1/31 8:00:00。

2020-10-13 20:43:20,745 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误9：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 11:00:00，计算结束时间是：2020/1/31 12:00:00。

2020-10-13 20:43:21,005 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误10：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 8:00:00，计算结束时间是：2020/1/31 9:00:00。

2020-10-13 20:43:21,966 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误11：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 12:00:00，计算结束时间是：2020/1/31 13:00:00。

2020-10-13 20:43:22,506 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误12：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 9:00:00，计算结束时间是：2020/1/31 10:00:00。

2020-10-13 20:43:23,405 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误13：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 13:00:00，计算结束时间是：2020/1/31 14:00:00。

2020-10-13 20:43:23,707 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误14：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 10:00:00，计算结束时间是：2020/1/31 11:00:00。

2020-10-13 20:43:24,420 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误15：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 14:00:00，计算结束时间是：2020/1/31 15:00:00。

2020-10-13 20:43:24,573 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误16：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 11:00:00，计算结束时间是：2020/1/31 12:00:00。

2020-10-13 20:43:25,569 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误17：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 15:00:00，计算结束时间是：2020/1/31 16:00:00。

2020-10-13 20:43:25,697 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误18：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 12:00:00，计算结束时间是：2020/1/31 13:00:00。

2020-10-13 20:43:26,800 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误19：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 16:00:00，计算结束时间是：2020/1/31 17:00:00。

2020-10-13 20:43:26,933 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误20：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 13:00:00，计算结束时间是：2020/1/31 14:00:00。

2020-10-13 20:43:27,926 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误21：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 17:00:00，计算结束时间是：2020/1/31 18:00:00。

2020-10-13 20:43:28,059 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误22：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 14:00:00，计算结束时间是：2020/1/31 15:00:00。

2020-10-13 20:43:29,387 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误23：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 18:00:00，计算结束时间是：2020/1/31 19:00:00。

2020-10-13 20:43:29,574 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误24：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 15:00:00，计算结束时间是：2020/1/31 16:00:00。

2020-10-13 20:43:30,974 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误25：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 19:00:00，计算结束时间是：2020/1/31 20:00:00。

2020-10-13 20:43:31,208 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误26：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 16:00:00，计算结束时间是：2020/1/31 17:00:00。

2020-10-13 20:43:32,605 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误27：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 20:00:00，计算结束时间是：2020/1/31 21:00:00。

2020-10-13 20:43:32,736 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误28：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 17:00:00，计算结束时间是：2020/1/31 18:00:00。

2020-10-13 20:43:33,580 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误29：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 21:00:00，计算结束时间是：2020/1/31 22:00:00。

2020-10-13 20:43:33,697 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误30：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 18:00:00，计算结束时间是：2020/1/31 19:00:00。

2020-10-13 20:43:34,522 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误31：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 22:00:00，计算结束时间是：2020/1/31 23:00:00。

2020-10-13 20:43:34,838 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误32：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 19:00:00，计算结束时间是：2020/1/31 20:00:00。

2020-10-13 20:43:35,669 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误33：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：100-MPVBaseShort，计算起始时间是：2020/1/31 23:00:00，计算结束时间是：2020/2/1 0:00:00。

2020-10-13 20:43:35,789 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误34：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 20:00:00，计算结束时间是：2020/1/31 21:00:00。

2020-10-13 20:43:36,128 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误35：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 21:00:00，计算结束时间是：2020/1/31 22:00:00。

2020-10-13 20:43:36,511 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误36：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 22:00:00，计算结束时间是：2020/1/31 23:00:00。

2020-10-13 20:43:36,872 [15] FATAL PSLCalcu.AppRunForm - 计算引擎错误37：计算模块内部意外错误!
——计算错误详细信息：MPVBase短周期数据录入数据库是失败。
——计算模块的名称是：101-MPVBaseShort，计算起始时间是：2020/1/31 23:00:00，计算结束时间是：2020/2/1 0:00:00。
