
2020-04-30 14:26:19,957 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：520-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,016 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误2：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：521-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,061 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误3：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：522-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,131 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误4：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：523-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,183 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误5：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：524-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,235 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误6：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：525-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,279 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误7：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：526-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,330 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误8：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：527-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,378 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误9：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：528-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,429 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误10：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：529-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,473 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误11：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：530-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,523 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误12：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：531-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,568 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误13：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：532-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,614 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误14：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：533-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,660 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误15：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：534-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,708 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误16：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：535-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,753 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误17：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：536-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,802 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误18：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：537-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,847 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误19：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：538-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,889 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误20：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：539-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,937 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误21：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：540-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:20,985 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误22：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：541-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,030 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误23：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：542-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,076 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误24：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：543-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,127 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误25：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：544-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,180 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误26：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：545-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,229 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误27：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：546-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,275 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误28：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：547-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,321 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误29：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：548-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,368 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误30：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：549-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,418 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误31：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：550-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,463 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误32：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：551-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,509 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误33：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：552-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,555 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误34：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：553-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,602 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误35：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：554-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,647 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误36：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：555-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,691 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误37：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：556-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,738 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误38：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：557-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,782 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误39：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：558-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,827 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误40：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：559-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,877 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误41：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：560-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,924 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误42：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：561-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:21,981 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误43：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：562-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,030 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误44：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：563-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,078 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误45：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：564-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,127 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误46：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：565-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,173 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误47：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：566-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,227 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误48：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：567-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,273 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误49：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：568-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,321 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误50：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：569-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,374 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误51：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：570-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,422 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误52：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：571-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,470 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误53：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：572-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,531 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误54：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：573-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,577 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误55：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：574-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,622 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误56：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：575-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,666 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误57：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：576-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,720 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误58：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：577-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,768 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误59：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：578-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,816 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误60：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：579-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,866 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误61：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：580-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,924 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误62：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：581-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:22,981 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误63：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：582-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,027 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误64：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：583-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,076 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误65：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：584-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,120 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误66：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：585-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,169 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误67：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：586-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,217 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误68：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：587-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,263 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误69：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：588-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,313 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误70：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：589-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,365 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误71：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：590-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,409 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误72：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：591-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,464 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误73：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：592-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,525 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误74：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：593-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,576 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误75：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：594-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,622 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误76：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：595-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,672 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误77：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：596-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,725 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误78：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：597-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,771 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误79：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：598-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,817 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误80：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：599-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,866 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误81：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：600-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,914 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误82：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：601-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:23,963 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误83：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：602-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,021 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误84：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：603-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,075 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误85：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：604-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,122 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误86：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：605-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,171 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误87：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：606-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,220 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误88：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：607-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,269 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误89：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：608-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,318 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误90：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：609-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,371 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误91：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：610-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,423 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误92：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：611-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,470 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误93：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：612-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,517 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误94：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：613-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,563 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误95：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：614-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,609 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误96：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：615-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,656 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误97：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：616-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,702 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误98：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：617-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,778 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误99：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：618-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,824 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误100：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：619-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,871 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误101：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：620-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,921 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误102：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：621-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:24,967 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误103：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：622-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,012 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误104：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：623-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,073 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误105：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：624-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,121 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误106：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：625-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,172 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误107：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：626-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,218 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误108：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：627-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,266 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误109：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：628-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,326 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误110：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：629-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,375 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误111：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：630-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,424 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误112：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：631-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,475 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误113：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：632-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,523 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误114：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：633-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,570 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误115：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：634-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,622 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误116：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：635-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,671 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误117：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：636-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,715 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误118：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：637-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,767 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误119：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：638-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,815 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误120：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：639-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,863 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误121：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：640-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,916 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误122：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：641-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:25,962 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误123：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：642-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,007 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误124：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：643-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,050 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误125：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：644-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,103 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误126：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：645-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,151 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误127：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：646-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,200 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误128：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：647-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,246 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误129：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：648-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,293 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误130：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：649-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,339 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误131：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：650-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,386 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误132：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：651-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,439 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误133：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：652-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,483 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误134：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：653-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,528 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误135：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：654-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,575 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误136：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：655-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,624 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误137：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：656-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,669 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误138：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：657-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,720 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误139：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：658-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,767 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误140：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：659-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,814 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误141：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：660-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,860 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误142：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：661-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,907 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误143：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：662-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:26,953 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误144：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：663-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,002 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误145：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：664-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,049 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误146：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：665-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,093 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误147：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：666-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,146 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误148：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：667-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,191 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误149：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：668-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,240 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误150：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：669-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,285 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误151：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：670-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,329 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误152：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：671-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,375 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误153：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：672-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,428 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误154：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：673-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,479 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误155：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：674-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,528 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误156：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：675-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,575 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误157：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：676-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,624 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误158：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：677-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,674 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误159：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：678-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,725 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误160：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：679-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,772 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误161：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：680-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,818 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误162：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：681-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,867 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误163：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：682-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,915 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误164：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：683-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:27,965 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误165：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：684-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,011 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误166：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：685-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,056 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误167：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：686-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,101 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误168：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：687-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,146 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误169：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：688-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,200 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误170：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：689-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,246 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误171：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：690-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,294 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误172：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：691-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,341 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误173：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：692-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,387 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误174：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：693-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,439 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误175：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：694-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,486 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误176：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：695-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,534 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误177：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：696-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,585 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误178：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：697-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,631 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误179：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：698-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,679 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误180：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：699-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,731 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误181：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：700-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,779 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误182：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：701-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,823 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误183：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：702-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,868 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误184：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：703-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,918 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误185：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：704-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:28,963 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误186：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：705-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,013 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误187：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：706-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,060 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误188：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：707-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,108 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误189：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：708-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,156 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误190：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：709-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,203 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误191：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：710-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,251 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误192：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：711-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,299 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误193：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：712-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,344 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误194：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：713-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,391 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误195：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：714-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,447 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误196：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：715-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,495 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误197：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：716-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,541 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误198：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：717-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,591 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误199：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：718-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,636 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误200：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：719-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,688 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误201：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：720-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,733 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误202：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：721-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,785 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误203：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：722-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,829 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误204：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：723-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,879 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误205：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：724-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,924 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误206：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：725-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:29,976 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误207：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：726-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,022 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误208：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：727-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,068 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误209：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：728-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,116 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误210：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：729-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,162 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误211：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：730-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,209 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误212：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：731-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,258 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误213：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：732-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,318 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误214：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：733-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,375 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误215：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：734-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,424 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误216：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：735-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,470 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误217：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：736-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,521 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误218：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：737-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,565 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误219：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：738-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,611 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误220：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：739-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,670 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误221：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：740-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,714 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误222：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：741-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,760 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误223：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：742-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,809 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误224：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：743-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,864 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误225：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：744-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,907 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误226：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：745-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:30,955 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误227：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：746-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,001 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误228：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：747-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,048 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误229：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：748-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,092 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误230：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：749-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,137 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误231：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：750-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,182 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误232：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：751-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,232 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误233：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：752-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,276 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误234：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：753-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,322 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误235：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：754-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,369 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误236：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：755-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,412 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误237：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：756-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,460 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误238：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：757-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,504 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误239：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：758-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,549 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误240：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：759-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,596 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误241：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：760-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,642 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误242：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：761-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,695 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误243：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：762-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,740 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误244：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：763-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,795 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误245：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：764-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,847 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误246：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：765-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,895 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误247：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：766-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:31,945 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误248：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：767-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,011 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误249：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：768-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,060 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误250：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：769-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,108 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误251：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：770-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,162 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误252：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：771-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,211 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误253：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：772-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,255 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误254：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：773-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,306 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误255：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：774-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,354 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误256：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：775-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,409 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误257：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：776-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,457 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误258：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：777-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,504 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误259：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：778-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,550 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误260：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：779-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,598 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误261：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：780-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,646 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误262：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：781-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,692 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误263：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：782-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,736 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误264：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：783-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,783 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误265：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：784-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,830 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误266：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：785-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,877 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误267：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：786-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,928 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误268：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：787-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:32,977 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误269：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：788-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,023 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误270：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：789-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,069 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误271：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：790-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,119 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误272：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：791-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,170 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误273：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：792-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,215 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误274：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：793-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,263 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误275：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：794-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,308 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误276：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：795-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,365 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误277：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：796-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,410 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误278：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：797-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,462 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误279：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：798-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,511 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误280：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：799-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,556 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误281：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：800-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,603 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误282：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：801-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,651 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误283：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：802-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,708 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误284：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：803-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,755 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误285：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：804-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,806 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误286：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：805-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,853 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误287：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：806-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,907 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误288：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：807-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:33,950 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误289：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：808-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,003 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误290：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：809-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,047 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误291：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：810-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,096 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误292：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：811-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,143 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误293：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：812-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,190 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误294：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：813-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,237 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误295：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：814-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,285 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误296：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：815-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,331 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误297：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：816-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,382 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误298：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：817-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,432 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误299：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：818-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,478 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误300：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：819-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,531 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误301：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：820-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,578 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误302：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：821-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,623 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误303：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：822-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,679 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误304：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：823-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,724 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误305：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：824-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,769 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误306：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：825-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,813 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误307：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：826-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,860 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误308：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：827-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,905 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误309：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：828-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,950 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误310：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：829-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:34,996 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误311：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：830-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,044 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误312：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：831-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,090 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误313：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：832-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,137 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误314：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：833-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,186 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误315：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：834-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,233 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误316：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：835-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,279 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误317：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：836-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,326 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误318：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：837-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,372 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误319：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：838-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,424 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误320：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：839-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,468 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误321：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：840-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,522 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误322：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：841-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,566 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误323：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：842-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,612 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误324：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：843-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,659 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误325：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：844-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,709 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误326：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：845-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,752 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误327：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：846-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,799 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误328：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：847-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,846 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误329：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：848-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,891 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误330：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：849-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,941 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误331：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：850-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:35,988 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误332：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：851-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,031 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误333：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：852-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,077 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误334：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：853-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,128 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误335：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：854-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,179 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误336：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：855-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,226 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误337：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：856-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,272 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误338：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：857-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,317 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误339：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：858-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,366 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误340：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：859-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,412 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误341：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：860-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,457 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误342：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：861-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,507 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误343：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：862-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,555 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误344：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：863-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,602 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误345：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：864-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,652 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误346：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：865-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,699 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误347：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：866-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,745 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误348：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：867-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,791 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误349：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：868-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,837 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误350：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：869-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,881 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误351：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：870-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,926 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误352：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：871-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:36,971 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误353：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：872-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,023 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误354：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：873-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,074 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误355：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：874-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,119 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误356：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：875-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,162 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误357：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：876-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,210 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误358：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：877-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,254 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误359：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：878-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,305 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误360：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：879-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,350 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误361：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：880-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,394 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误362：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：881-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,451 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误363：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：882-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,505 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误364：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：883-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,562 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误365：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：884-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,609 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误366：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：885-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,665 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误367：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：886-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,718 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误368：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：887-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,776 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误369：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：888-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,821 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误370：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：889-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,871 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误371：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：890-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,917 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误372：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：891-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:37,964 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误373：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：892-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,009 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误374：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：893-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,056 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误375：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：894-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,101 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误376：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：895-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,146 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误377：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：896-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,197 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误378：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：897-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,242 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误379：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：898-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,289 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误380：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：899-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,336 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误381：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：900-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,385 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误382：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：901-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,434 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误383：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：902-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,480 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误384：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：903-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,528 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误385：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：904-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,580 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误386：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：905-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,627 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误387：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：906-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,677 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误388：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：907-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,730 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误389：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：908-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,777 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误390：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：909-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,822 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误391：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：910-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,868 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误392：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：911-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,915 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误393：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：912-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:38,972 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误394：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：913-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:39,022 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误395：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：914-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:39,080 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误396：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：915-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:39,139 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误397：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：916-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:39,185 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误398：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：917-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:39,240 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误399：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：918-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:39,284 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误400：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：919-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:39,335 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误401：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：920-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:39,381 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误402：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：921-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:39,430 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误403：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：922-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:39,478 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误404：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：923-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:39,523 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误405：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：924-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:39,575 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误406：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：925-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:39,624 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误407：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：926-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:39,670 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误408：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：927-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:39,715 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误409：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：928-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:39,772 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误410：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：929-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:39,826 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误411：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：930-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:39,871 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误412：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：931-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。

2020-04-30 14:26:39,923 [6] FATAL PSLCalcu.AppRunForm - 计算引擎错误413：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：932-MPVBase，计算起始时间是：2020/4/29 5:00:00，计算结束时间是：2020/4/29 6:00:00。
