
2020-04-28 12:50:34,731 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：读取实时数据错误，RTDBDAO层出错!
——计算模块的名称是：41-MOPCFilter2One，计算起始时间是：2020/4/1 0:00:00，计算结束时间是：2020/4/1 0:01:00。

2020-04-28 12:50:34,731 [20] FATAL PSLCalcu.AppRunForm - 计算引擎错误2：读取实时数据错误，RTDBDAO层出错!
——计算模块的名称是：30-MOPCFilter2One，计算起始时间是：2020/4/1 0:00:00，计算结束时间是：2020/4/1 0:01:00。

2020-04-28 12:50:34,732 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误3：读取实时数据错误，RTDBDAO层出错!
——计算模块的名称是：8-MOPCFilter2One，计算起始时间是：2020/4/1 0:00:00，计算结束时间是：2020/4/1 0:01:00。

2020-04-28 12:51:07,470 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：读算写错误中未知错误!!
——计算错误详细信息：System.Threading.ThreadAbortException: 正在中止线程。
   在 PSLCalcu.PSLDataDAO.WriteOrUpdate(UInt32 tagid, List`1 pvalues, DateTime startdate, DateTime enddate) 位置 d:\c#\PSLCalcu_Test\PSLCalcu\DAO\PSLDataDAO.cs:行号 360
   在 PSLCalcu.CurrentCalcuEngine.actualCalcu(LogHelper logHelper, PSLCalcuItem pslcalcuitem, Int32 CALCUMODULE_THRESHOLD, Int64& errorCount, Int64& warningCount, Int64& calcount, Int64& beforeCalcount) 位置 d:\c#\PSLCalcu_Test\PSLCalcu\Support\CurrentCalcuEngine.cs:行号 566。
——计算模块的名称是：387-MPVBase，计算起始时间是：2020/4/1 0:00:00，计算结束时间是：2020/4/2 0:00:00。

2020-04-28 13:02:12,531 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：70-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:12,531 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误2：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：52-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:12,594 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误3：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：71-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:12,626 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误4：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：53-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:12,668 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误5：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：72-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:12,714 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误6：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：54-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:12,750 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误7：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：73-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:12,803 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误8：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：55-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:12,825 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误9：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：74-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:12,899 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误10：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：75-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:12,916 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误11：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：56-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:12,992 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误12：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：76-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:13,002 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误13：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：57-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:13,066 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误14：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：58-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:13,091 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误15：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：77-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:13,161 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误16：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：59-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:13,170 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误17：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：78-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:13,243 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误18：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：79-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:13,290 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误19：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：60-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:13,354 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误20：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：80-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:13,460 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误21：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：61-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:13,470 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误22：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：81-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:13,564 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误23：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：62-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:13,589 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误24：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：82-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:13,666 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误25：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：83-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:13,678 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误26：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：63-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:13,731 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误27：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：84-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:13,852 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误28：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：85-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:13,860 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误29：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：64-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:13,951 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误30：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：65-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:13,966 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误31：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：86-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:14,028 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误32：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：66-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:14,115 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误33：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：87-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:14,121 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误34：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：67-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:14,207 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误35：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：88-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:14,207 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误36：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：68-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:14,271 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误37：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：89-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:14,306 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误38：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：69-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:14,346 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误39：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：90-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:02:14,405 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误40：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：91-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:18:56,105 [13] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：读取实时数据错误，RTDBDAO层出错!
——计算模块的名称是：41-MOPCFilter2One，计算起始时间是：2020/4/1 0:00:00，计算结束时间是：2020/4/1 0:01:00。

2020-04-28 13:18:56,105 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误2：读取实时数据错误，RTDBDAO层出错!
——计算模块的名称是：30-MOPCFilter2One，计算起始时间是：2020/4/1 0:00:00，计算结束时间是：2020/4/1 0:01:00。

2020-04-28 13:18:56,105 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误3：读取实时数据错误，RTDBDAO层出错!
——计算模块的名称是：8-MOPCFilter2One，计算起始时间是：2020/4/1 0:00:00，计算结束时间是：2020/4/1 0:01:00。

2020-04-28 13:29:56,252 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：读算写错误中未知错误!!
——计算错误详细信息：System.Threading.ThreadAbortException: 正在中止线程。
   在 PSLCalcu.PSLDataDAO.WriteOrUpdate(UInt32 tagid, List`1 pvalues, DateTime startdate, DateTime enddate) 位置 d:\c#\PSLCalcu_Test\PSLCalcu\DAO\PSLDataDAO.cs:行号 360
   在 PSLCalcu.CurrentCalcuEngine.actualCalcu(LogHelper logHelper, PSLCalcuItem pslcalcuitem, Int32 CALCUMODULE_THRESHOLD, Int64& errorCount, Int64& warningCount, Int64& calcount, Int64& beforeCalcount) 位置 d:\c#\PSLCalcu_Test\PSLCalcu\Support\CurrentCalcuEngine.cs:行号 459。
——计算模块的名称是：88-MPVBase，计算起始时间是：2020/4/1 5:00:00，计算结束时间是：2020/4/1 6:00:00。

2020-04-28 13:35:38,536 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：52-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:38,585 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误2：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：53-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:38,635 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误3：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：54-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:38,683 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误4：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：55-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:38,732 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误5：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：56-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:38,789 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误6：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：57-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:38,839 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误7：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：58-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:38,883 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误8：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：59-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:38,931 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误9：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：60-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:38,973 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误10：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：61-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,015 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误11：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：62-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,060 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误12：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：63-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,106 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误13：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：64-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,148 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误14：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：65-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,190 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误15：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：66-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,232 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误16：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：67-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,274 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误17：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：68-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,315 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误18：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：69-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,357 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误19：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：70-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,405 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误20：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：71-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,447 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误21：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：72-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,490 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误22：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：73-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,531 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误23：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：74-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,574 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误24：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：75-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,617 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误25：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：76-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,662 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误26：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：77-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,707 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误27：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：78-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,751 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误28：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：79-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,793 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误29：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：80-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,835 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误30：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：81-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,876 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误31：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：82-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,918 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误32：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：83-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:39,961 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误33：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：84-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:40,011 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误34：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：85-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:40,057 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误35：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：86-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:40,099 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误36：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：87-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:46,451 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：88-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:46,502 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误2：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：89-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:46,555 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误3：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：90-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:35:46,608 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误4：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：91-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:39:22,944 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：读算写错误中未知错误!!
——计算错误详细信息：System.Threading.ThreadAbortException: 正在中止线程。
   在 PSLCalcu.PSLDataDAO.WriteOrUpdate(UInt32 tagid, List`1 pvalues, DateTime startdate, DateTime enddate) 位置 d:\c#\PSLCalcu_Test\PSLCalcu\DAO\PSLDataDAO.cs:行号 360
   在 PSLCalcu.CurrentCalcuEngine.actualCalcu(LogHelper logHelper, PSLCalcuItem pslcalcuitem, Int32 CALCUMODULE_THRESHOLD, Int64& errorCount, Int64& warningCount, Int64& calcount, Int64& beforeCalcount) 位置 d:\c#\PSLCalcu_Test\PSLCalcu\Support\CurrentCalcuEngine.cs:行号 459。
——计算模块的名称是：267-MPVBase，计算起始时间是：2020/4/1 20:00:00，计算结束时间是：2020/4/1 21:00:00。

2020-04-28 13:41:25,583 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：计算模块内部意外错误!
——计算错误详细信息：System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException()
   在 System.Collections.Generic.List`1.get_Item(Int32 index)
   在 PSLCalcu.Module.MDeviationS.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\Adv_Deviation\MDeviationS.cs:行号 242。
——计算模块的名称是：238-MDeviationS，计算起始时间是：2020/4/1 0:43:00，计算结束时间是：2020/4/1 0:44:00。

2020-04-28 13:41:27,255 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：读算写错误中未知错误!!
——计算错误详细信息：System.Threading.ThreadAbortException: 正在中止线程。
   在 PSLCalcu.PSLDataDAO.WriteOrUpdate(UInt32 tagid, List`1 pvalues, DateTime startdate, DateTime enddate) 位置 d:\c#\PSLCalcu_Test\PSLCalcu\DAO\PSLDataDAO.cs:行号 360
   在 PSLCalcu.CurrentCalcuEngine.actualCalcu(LogHelper logHelper, PSLCalcuItem pslcalcuitem, Int32 CALCUMODULE_THRESHOLD, Int64& errorCount, Int64& warningCount, Int64& calcount, Int64& beforeCalcount) 位置 d:\c#\PSLCalcu_Test\PSLCalcu\Support\CurrentCalcuEngine.cs:行号 459。
——计算模块的名称是：351-MPVBase，计算起始时间是：2020/4/2 16:00:00，计算结束时间是：2020/4/2 17:00:00。

2020-04-28 13:41:27,496 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误2：写计算结果错误，PSLDataDAO层出错!
——计算模块的名称是：263-MPVBase，计算起始时间是：2020/4/2 17:00:00，计算结束时间是：2020/4/2 18:00:00。

2020-04-28 13:43:02,064 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：计算模块内部意外错误!
——计算错误详细信息：System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException()
   在 System.Collections.Generic.List`1.RemoveAt(Int32 index)
   在 PSLCalcu.Module.MDeviationS.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\Adv_Deviation\MDeviationS.cs:行号 242。
——计算模块的名称是：220-MDeviationS，计算起始时间是：2020/4/1 0:51:00，计算结束时间是：2020/4/1 0:52:00。

2020-04-28 13:52:08,202 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：70-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:08,220 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误2：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：52-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:08,283 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误3：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：71-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:08,302 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误4：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：53-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:08,362 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误5：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：72-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:08,388 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误6：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：54-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:08,470 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误7：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：55-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:08,475 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误8：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：73-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:08,549 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误9：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：74-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:08,568 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误10：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：56-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:08,657 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误12：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：57-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:08,657 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误12：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：75-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:08,728 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误13：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：76-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:08,758 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误14：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：58-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:08,824 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误15：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：77-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:08,866 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误16：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：59-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:08,924 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误17：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：78-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:08,964 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误18：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：60-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,005 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误19：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：79-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,061 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误20：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：61-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,091 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误21：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：80-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,176 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误22：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：62-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,182 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误23：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：81-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,261 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误24：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：63-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,284 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误25：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：82-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,373 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误26：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：64-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,382 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误27：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：83-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,465 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误28：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：65-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,483 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误29：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：84-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,549 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误30：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：85-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,572 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误31：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：66-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,645 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误32：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：86-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,674 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误33：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：67-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,727 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误34：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：87-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,777 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误35：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：68-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,837 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误36：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：88-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,859 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误37：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：69-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:09,921 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误38：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：89-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:10,004 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误39：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：90-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:10,075 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误40：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：91-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:52:44,785 [19] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：计算模块内部意外错误!
——计算错误详细信息：System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException()
   在 System.Collections.Generic.List`1.RemoveAt(Int32 index)
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 401。
——计算模块的名称是：70-MPVBase，计算起始时间是：2020/4/1 2:00:00，计算结束时间是：2020/4/1 3:00:00。

2020-04-28 13:53:14,496 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：70-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:14,515 [20] FATAL PSLCalcu.AppRunForm - 计算引擎错误2：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：52-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:14,566 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误3：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：71-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:14,596 [20] FATAL PSLCalcu.AppRunForm - 计算引擎错误4：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：53-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:14,647 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误5：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：72-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:14,679 [20] FATAL PSLCalcu.AppRunForm - 计算引擎错误6：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：54-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:14,724 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误7：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：73-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:14,768 [20] FATAL PSLCalcu.AppRunForm - 计算引擎错误8：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：55-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:14,818 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误9：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：74-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:14,857 [20] FATAL PSLCalcu.AppRunForm - 计算引擎错误10：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：56-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:14,914 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误11：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：75-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:14,954 [20] FATAL PSLCalcu.AppRunForm - 计算引擎错误12：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：57-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:14,989 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误13：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：76-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,040 [20] FATAL PSLCalcu.AppRunForm - 计算引擎错误14：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：58-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,087 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误15：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：77-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,127 [20] FATAL PSLCalcu.AppRunForm - 计算引擎错误16：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：59-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,163 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误17：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：78-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,217 [20] FATAL PSLCalcu.AppRunForm - 计算引擎错误18：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：60-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,247 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误19：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：79-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,314 [20] FATAL PSLCalcu.AppRunForm - 计算引擎错误20：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：61-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,354 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误21：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：80-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,423 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误22：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：81-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,443 [20] FATAL PSLCalcu.AppRunForm - 计算引擎错误23：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：62-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,511 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误24：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：82-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,560 [20] FATAL PSLCalcu.AppRunForm - 计算引擎错误25：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：63-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,623 [20] FATAL PSLCalcu.AppRunForm - 计算引擎错误26：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：64-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,682 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误27：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：83-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,704 [20] FATAL PSLCalcu.AppRunForm - 计算引擎错误28：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：65-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,755 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误29：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：84-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,787 [20] FATAL PSLCalcu.AppRunForm - 计算引擎错误30：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：66-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,827 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误31：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：85-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,869 [20] FATAL PSLCalcu.AppRunForm - 计算引擎错误32：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：67-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,907 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误33：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：86-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,943 [20] FATAL PSLCalcu.AppRunForm - 计算引擎错误34：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：68-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:15,991 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误35：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：87-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:16,049 [20] FATAL PSLCalcu.AppRunForm - 计算引擎错误36：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：69-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:16,097 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误37：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：88-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:16,154 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误38：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：89-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:16,210 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误39：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：90-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:53:16,268 [22] FATAL PSLCalcu.AppRunForm - 计算引擎错误40：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：91-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:07,688 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：52-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:07,738 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误2：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：53-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:07,781 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误3：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：54-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:07,833 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误4：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：55-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:07,877 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误5：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：56-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:07,927 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误6：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：57-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:07,980 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误7：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：58-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,026 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误8：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：59-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,077 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误9：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：60-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,121 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误10：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：61-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,171 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误11：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：62-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,214 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误12：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：63-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,262 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误13：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：64-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,303 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误14：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：65-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,345 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误15：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：66-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,387 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误16：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：67-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,430 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误17：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：68-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,472 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误18：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：69-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,514 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误19：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：70-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,555 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误20：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：71-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,600 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误21：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：72-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,646 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误22：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：73-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,691 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误23：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：74-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,739 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误24：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：75-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,783 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误25：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：76-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,828 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误26：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：77-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,870 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误27：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：78-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,913 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误28：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：79-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:08,974 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误29：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：80-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:09,016 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误30：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：81-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:09,058 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误31：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：82-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:09,099 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误32：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：83-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:09,141 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误33：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：84-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:09,184 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误34：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：85-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:09,226 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误35：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：86-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:09,270 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误36：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：87-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:09,311 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误37：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：88-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:09,353 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误38：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：89-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:09,395 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误39：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：90-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 13:57:09,440 [14] FATAL PSLCalcu.AppRunForm - 计算引擎错误40：计算模块内部意外错误!
——计算错误详细信息：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 519。
——计算模块的名称是：91-MPVBase，计算起始时间是：2020/4/1 12:00:00，计算结束时间是：2020/4/1 13:00:00。

2020-04-28 17:42:16,548 [21] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：计算模块内部意外错误!
——计算错误详细信息：System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException()
   在 System.Collections.Generic.List`1.RemoveAt(Int32 index)
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 401。
——计算模块的名称是：79-MPVBase，计算起始时间是：2020/4/1 19:00:00，计算结束时间是：2020/4/1 20:00:00。

2020-04-28 17:57:06,516 [10] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：读算写错误中未知错误!!
——计算错误详细信息：System.Threading.ThreadAbortException: 正在中止线程。
   在 PSLCalcu.PSLDataDAO.WriteOrUpdate(UInt32 tagid, List`1 pvalues, DateTime startdate, DateTime enddate) 位置 d:\c#\PSLCalcu_Test\PSLCalcu\DAO\PSLDataDAO.cs:行号 360
   在 PSLCalcu.CurrentCalcuEngine.actualCalcu(LogHelper logHelper, PSLCalcuItem pslcalcuitem, Int32 CALCUMODULE_THRESHOLD, Int64& errorCount, Int64& warningCount, Int64& calcount, Int64& beforeCalcount, DateTime stop) 位置 d:\c#\PSLCalcu_Test\PSLCalcu\Support\CurrentCalcuEngine.cs:行号 457。
——计算模块的名称是：3967-MPVBase，计算起始时间是：2020/4/28 16:00:00，计算结束时间是：2020/4/28 17:00:00。

2020-04-28 18:00:26,231 [16] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：计算模块内部意外错误!
——计算错误详细信息：System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException()
   在 System.Collections.Generic.List`1.RemoveAt(Int32 index)
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 401。
——计算模块的名称是：1982-MPVBase，计算起始时间是：2020/4/28 16:00:00，计算结束时间是：2020/4/28 17:00:00。

2020-04-28 18:00:41,341 [10] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：计算模块内部意外错误!
——计算错误详细信息：System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException()
   在 System.Collections.Generic.List`1.RemoveAt(Int32 index)
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 401。
——计算模块的名称是：1184-MPVBase，计算起始时间是：2020/4/28 17:00:00，计算结束时间是：2020/4/28 18:00:00。

2020-04-28 18:01:08,669 [18] FATAL PSLCalcu.AppRunForm - 计算引擎错误2：计算模块内部意外错误!
——计算错误详细信息：System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException()
   在 System.Collections.Generic.List`1.RemoveAt(Int32 index)
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 401。
——计算模块的名称是：585-MPVBase，计算起始时间是：2020/4/28 17:00:00，计算结束时间是：2020/4/28 18:00:00。

2020-04-28 18:18:38,545 [17] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：计算模块内部意外错误!
——计算错误详细信息：System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException()
   在 System.Collections.Generic.List`1.RemoveAt(Int32 index)
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 401。
——计算模块的名称是：3304-MPVBase，计算起始时间是：2020/4/28 16:00:00，计算结束时间是：2020/4/28 17:00:00。

2020-04-28 18:19:38,592 [21] FATAL PSLCalcu.AppRunForm - 计算引擎错误1：计算模块内部意外错误!
——计算错误详细信息：System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException()
   在 System.Collections.Generic.List`1.RemoveAt(Int32 index)
   在 PSLCalcu.Module.MPVBase.Calcu(List`1[] inputs, CalcuInfo calcuinfo) 位置 d:\c#\PSLCalcu_Test\PSLCalcu.Module\NewBase\MPVBase.cs:行号 401。
——计算模块的名称是：2191-MPVBase，计算起始时间是：2020/4/28 17:00:00，计算结束时间是：2020/4/28 18:00:00。
