CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteMPVUTNVDetail`(
    in parentid int
)
BEGIN
    DELETE FROM `psldb`.`psl_mpvutnv_detail`
WHERE `pid`=parentid;

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteTimeValue`(
    in pid int
)
BEGIN
    DELETE FROM `psldb`.`psl_timedata`
WHERE `parentid`=pid;

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `getColumnID`(
    in cName varchar(45)
)
BEGIN
    SELECT * FROM `psldb`.`psl_columndata` where `columnName`=cName;
 
END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertM2AnalogDiv`(
    in DivV varchar(45),
    in DivAbsV varchar(45)
)
BEGIN
    INSERT INTO `psldb`.`psl_m2analogdiv`
(`Div`,
`DivAbs`)
VALUES
(DivV,
DivAbsV);

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertMDevLimit`(
    in DevHHNV varchar(45),
        in DevHHTV varchar(45),
        in DevHHRV varchar(45),
        in DevHHTMaxV varchar(45),
        in DevHHAV varchar(45),
        in DevHHETV varchar(45),
        in DevHNV varchar(45),
        in DevHTV varchar(45),
        in DevHRV varchar(45),
        in DevHTMaxV varchar(45),
        in DevHAV varchar(45),
        in DevHETV varchar(45),
        in DevRPNV varchar(45),
        in DevRPTV varchar(45),
        in DevRPRV varchar(45),
        in DevRPTMaxV varchar(45),
        in DevRPAV varchar(45),
        in DevRPETV varchar(45),
        in Dev0PNV varchar(45),
        in Dev0PTV varchar(45),
        in Dev0PRV varchar(45),
        in Dev0PTMaxV varchar(45),
        in Dev0PAV varchar(45),
        in Dev0PETV varchar(45),
        in Dev0NNV varchar(45),
        in Dev0NTV varchar(45),
        in Dev0NRV varchar(45),
        in Dev0NTMaxV varchar(45),
        in Dev0NAV varchar(45),
        in Dev0NETV varchar(45),
        in DevRNNV varchar(45),
        in DevRNTV varchar(45),
        in DevRNRV varchar(45),
        in DevRNTMaxV varchar(45),
        in DevRNAV varchar(45),
        in DevRNETV varchar(45),
        in DevLNV varchar(45),
        in DevLTV varchar(45),
        in DevLRV varchar(45),
        in DevLTMaxV varchar(45),
        in DevLAV varchar(45),
        in DevLETV varchar(45),
        in DevLLNV varchar(45),
        in DevLLTV varchar(45),
        in DevLLRV varchar(45),
        in DevLLTMaxV varchar(45),
        in DevLLAV varchar(45),
        in DevLLETV varchar(45),
        in Dev0HTV varchar(45),
        in Dev0HTRV varchar(45),
        in Dev0HHTV varchar(45),
        in Dev0HHTRV varchar(45),
        in Dev0LV varchar(45),
        in Dev0LRV varchar(45),
        in Dev0LLTV varchar(45),
        in Dev0LLTRV varchar(45),
        in DevHHLLTV varchar(45),
        in DevHHLLTRV varchar(45),
        in DevHLHHLLTV varchar(45),
        in DevHLHHLLRV varchar(45),
        in DevRPRMHLTV varchar(45),
        in DevRPRMHLTRV varchar(45),
        in Dev0RPRMTV varchar(45),
        in Dev0RPRMTRV varchar(45),
        in Dev0RPRMTMaxV varchar(45),
        in DevHLTV varchar(45),
        in DevHLTRV varchar(45),
        in DevHLTMaxV varchar(45),
        in DevPTV varchar(45),
        in DevPTRV varchar(45),
        in DevPTRTMaxV varchar(45),
        in DevNTV varchar(45),
        in DevNTRV varchar(45),
        in DevNTRTMaxV varchar(45),
        in typeV varchar(45),
        in yearV varchar(45),
        in monthV varchar(45),
        in dayV varchar(45),
        in hourV varchar(45)
)
BEGIN
    INSERT INTO `psldb`.`psl_mdevlimit`
(`DevHHN`,
`DevHHT`,
`DevHHR`,
`DevHHTMax`,
`DevHHA`,
`DevHHET`,
`DevHN`,
`DevHT`,
`DevHR`,
`DevHTMax`,
`DevHA`,
`DevHET`,
`DevRPN`,
`DevRPT`,
`DevRPR`,
`DevRPTMax`,
`DevRPA`,
`DevRPET`,
`Dev0PN`,
`Dev0PT`,
`Dev0PR`,
`Dev0PTMax`,
`Dev0PA`,
`Dev0PET`,
`Dev0NN`,
`Dev0NT`,
`Dev0NR`,
`Dev0NTMax`,
`Dev0NA`,
`Dev0NET`,
`DevRNN`,
`DevRNT`,
`DevRNR`,
`DevRNTMax`,
`DevRNA`,
`DevRNET`,
`DevLN`,
`DevLT`,
`DevLR`,
`DevLTMax`,
`DevLA`,
`DevLET`,
`DevLLN`,
`DevLLT`,
`DevLLR`,
`DevLLTMax`,
`DevLLA`,
`DevLLET`,
`Dev0HT`,
`Dev0HTR`,
`Dev0HHT`,
`Dev0HHTR`,
`Dev0L`,
`Dev0LR`,
`Dev0LLT`,
`Dev0LLTR`,
`DevHHLLT`,
`DevHHLLTR`,
`DevHLHHLLT`,
`DevHLHHLLR`,
`DevRPRMHLT`,
`DevRPRMHLTR`,
`Dev0RPRMT`,
`Dev0RPRMTR`,
`Dev0RPRMTMax`,
`DevHLT`,
`DevHLTR`,
`DevHLTMax`,
`DevPT`,
`DevPTR`,
`DevPTRTMax`,
`DevNT`,
`DevNTR`,
`DevNTRTMax`,
`yearvalue`,
`monthvalue`,
`dayvalue`,
`hourvalue`,
`tagId`)
VALUES
(DevHHNV,
        DevHHTV,
        DevHHRV,
        DevHHTMaxV,
        DevHHAV,
        DevHHETV,
        DevHNV,
        DevHTV,
        DevHRV,
        DevHTMaxV,
        DevHAV,
        DevHETV,
        DevRPNV,
        DevRPTV,
        DevRPRV,
        DevRPTMaxV,
        DevRPAV,
        DevRPETV,
        Dev0PNV,
        Dev0PTV,
        Dev0PRV,
        Dev0PTMaxV,
        Dev0PAV,
        Dev0PETV,
        Dev0NNV,
        Dev0NTV,
        Dev0NRV,
        Dev0NTMaxV,
        Dev0NAV,
        Dev0NETV,
        DevRNNV,
        DevRNTV,
        DevRNRV,
        DevRNTMaxV,
        DevRNAV,
        DevRNETV,
        DevLNV,
        DevLTV,
        DevLRV,
        DevLTMaxV,
        DevLAV,
        DevLETV,
        DevLLNV,
        DevLLTV,
        DevLLRV,
        DevLLTMaxV,
        DevLLAV,
        DevLLETV,
        Dev0HTV,
        Dev0HTRV,
        Dev0HHTV,
        Dev0HHTRV,
        Dev0LV,
        Dev0LRV,
        Dev0LLTV,
        Dev0LLTRV,
        DevHHLLTV,
        DevHHLLTRV,
        DevHLHHLLTV,
        DevHLHHLLRV,
        DevRPRMHLTV,
        DevRPRMHLTRV,
        Dev0RPRMTV,
        Dev0RPRMTRV,
        Dev0RPRMTMaxV,
        DevHLTV,
        DevHLTRV,
        DevHLTMaxV,
        DevPTV,
        DevPTRV,
        DevPTRTMaxV,
        DevNTV,
        DevNTRV,
        DevNTRTMaxV,
        yearV,
        monthV,
        dayV,
        hourV,
        typeV);
SELECT SCOPE_IDENTITY() as `lastid`;
END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertMDevLimitMulti`(
    in DevHHNOrderV TEXT,
        in DevHHTOrderV TEXT,
        in DevHHROrderV TEXT,
        in DevHHTMaxOrderV TEXT,
        in DevHHAOrderV TEXT,
        in DevHHETOrderV TEXT,
        in DevHNOrderV TEXT,
        in DevHTOrderV TEXT,
        in DevHROrderV TEXT,
        in DevHTMaxOrderV TEXT,
        in DevHAOrderV TEXT,
        in DevHETOrderV TEXT,
        in DevRPNOrderV TEXT,
        in DevRPTOrderV TEXT,
        in DevRPROrderV TEXT,
        in DevRPTMaxOrderV TEXT,
        in DevRPAOrderV TEXT,
        in DevRPETOrderV TEXT,
        in Dev0PNOrderV TEXT,
        in Dev0PTOrderV TEXT,
        in Dev0PROrderV TEXT,
        in Dev0PTMaxOrderV TEXT,
        in Dev0PAOrderV TEXT,
        in Dev0PETOrderV TEXT,
        in Dev0NNOrderV TEXT,
        in Dev0NTOrderV TEXT,
        in Dev0NROrderV TEXT,
        in Dev0NTMaxOrderV TEXT,
        in Dev0NAOrderV TEXT,
        in Dev0NETOrderV TEXT,
        in DevRNNOrderV TEXT,
        in DevRNTOrderV TEXT,
        in DevRNROrderV TEXT,
        in DevRNTMaxOrderV TEXT,
        in DevRNAOrderV TEXT,
        in DevRNETOrderV TEXT,
        in DevLNOrderV TEXT,
        in DevLTOrderV TEXT,
        in DevLROrderV TEXT,
        in DevLTMaxOrderV TEXT,
        in DevLAOrderV TEXT,
        in DevLETOrderV TEXT,
        in DevLLNOrderV TEXT,
        in DevLLTOrderV TEXT,
        in DevLLROrderV TEXT,
        in DevLLTMaxOrderV TEXT,
        in DevLLAOrderV TEXT,
        in DevLLETOrderV TEXT,
        in Dev0HTOrderV TEXT,
        in Dev0HTROrderV TEXT,
        in Dev0HHTOrderV TEXT,
        in Dev0HHTROrderV TEXT,
        in Dev0LOrderV TEXT,
        in Dev0LROrderV TEXT,
        in Dev0LLTOrderV TEXT,
        in Dev0LLTROrderV TEXT,
        in DevHHLLTOrderV TEXT,
        in DevHHLLTROrderV TEXT,
        in DevHLHHLLTOrderV TEXT,
        in DevHLHHLLROrderV TEXT,
        in DevRPRMHLTOrderV TEXT,
        in DevRPRMHLTROrderV TEXT,
        in Dev0RPRMTOrderV TEXT,
        in Dev0RPRMTROrderV TEXT,
        in Dev0RPRMTMaxOrderV TEXT,
        in DevHLTOrderV TEXT,
        in DevHLTROrderV TEXT,
        in DevHLTMaxOrderV TEXT,
        in DevPTOrderV TEXT,
        in DevPTROrderV TEXT,
        in DevPTRTMaxOrderV TEXT,
        in DevNTOrderV TEXT,
        in DevNTROrderV TEXT,
        in DevNTRTMaxOrderV TEXT
)
BEGIN
    INSERT INTO `psldb`.`psl_mdevlimitmulti`
(`DevHHNOrder`,
`DevHHTOrder`,
`DevHHROrder`,
`DevHHTMaxOrder`,
`DevHHAOrder`,
`DevHHETOrder`,
`DevHNOrder`,
`DevHTOrder`,
`DevHROrder`,
`DevHTMaxOrder`,
`DevHAOrder`,
`DevHETOrder`,
`DevRPNOrder`,
`DevRPTOrder`,
`DevRPROrder`,
`DevRPTMaxOrder`,
`DevRPAOrder`,
`DevRPETOrder`,
`Dev0PNOrder`,
`Dev0PTOrder`,
`Dev0PROrder`,
`Dev0PTMaxOrder`,
`Dev0PAOrder`,
`Dev0PETOrder`,
`Dev0NNOrder`,
`Dev0NTOrder`,
`Dev0NROrder`,
`Dev0NTMaxOrder`,
`Dev0NAOrder`,
`Dev0NETOrder`,
`DevRNNOrder`,
`DevRNTOrder`,
`DevRNROrder`,
`DevRNTMaxOrder`,
`DevRNAOrder`,
`DevRNETOrder`,
`DevLNOrder`,
`DevLTOrder`,
`DevLROrder`,
`DevLTMaxOrder`,
`DevLAOrder`,
`DevLETOrder`,
`DevLLNOrder`,
`DevLLTOrder`,
`DevLLROrder`,
`DevLLTMaxOrder`,
`DevLLAOrder`,
`DevLLETOrder`,
`Dev0HTOrder`,
`Dev0HTROrder`,
`Dev0HHTOrder`,
`Dev0HHTROrder`,
`Dev0LOrder`,
`Dev0LROrder`,
`Dev0LLTOrder`,
`Dev0LLTROrder`,
`DevHHLLTOrder`,
`DevHHLLTROrder`,
`DevHLHHLLTOrder`,
`DevHLHHLLROrder`,
`DevRPRMHLTOrder`,
`DevRPRMHLTROrder`,
`Dev0RPRMTOrder`,
`Dev0RPRMTROrder`,
`Dev0RPRMTMaxOrder`,
`DevHLTOrder`,
`DevHLTROrder`,
`DevHLTMaxOrder`,
`DevPTOrder`,
`DevPTROrder`,
`DevPTRTMaxOrder`,
`DevNTOrder`,
`DevNTROrder`,
`DevNTRTMaxOrder`)
VALUES
(DevHHNOrderV,
        DevHHTOrderV,
        DevHHROrderV,
        DevHHTMaxOrderV,
        DevHHAOrderV,
        DevHHETOrderV,
        DevHNOrderV,
        DevHTOrderV,
        DevHROrderV,
        DevHTMaxOrderV,
        DevHAOrderV,
        DevHETOrderV,
        DevRPNOrderV,
        DevRPTOrderV,
        DevRPROrderV,
        DevRPTMaxOrderV,
        DevRPAOrderV,
        DevRPETOrderV,
        Dev0PNOrderV,
        Dev0PTOrderV,
        Dev0PROrderV,
        Dev0PTMaxOrderV,
        Dev0PAOrderV,
        Dev0PETOrderV,
        Dev0NNOrderV,
        Dev0NTOrderV,
        Dev0NROrderV,
        Dev0NTMaxOrderV,
        Dev0NAOrderV,
        Dev0NETOrderV,
        DevRNNOrderV,
        DevRNTOrderV,
        DevRNROrderV,
        DevRNTMaxOrderV,
        DevRNAOrderV,
        DevRNETOrderV,
        DevLNOrderV,
        DevLTOrderV,
        DevLROrderV,
        DevLTMaxOrderV,
        DevLAOrderV,
        DevLETOrderV,
        DevLLNOrderV,
        DevLLTOrderV,
        DevLLROrderV,
        DevLLTMaxOrderV,
        DevLLAOrderV,
        DevLLETOrderV,
        Dev0HTOrderV,
        Dev0HTROrderV,
        Dev0HHTOrderV,
        Dev0HHTROrderV,
        Dev0LOrderV,
        Dev0LROrderV,
        Dev0LLTOrderV,
        Dev0LLTROrderV,
        DevHHLLTOrderV,
        DevHHLLTROrderV,
        DevHLHHLLTOrderV,
        DevHLHHLLROrderV,
        DevRPRMHLTOrderV,
        DevRPRMHLTROrderV,
        Dev0RPRMTOrderV,
        Dev0RPRMTROrderV,
        Dev0RPRMTMaxOrderV,
        DevHLTOrderV,
        DevHLTROrderV,
        DevHLTMaxOrderV,
        DevPTOrderV,
        DevPTROrderV,
        DevPTRTMaxOrderV,
        DevNTOrderV,
        DevNTROrderV,
        DevNTRTMaxOrderV);

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertMFDistribute22`(
    in D22AvgV varchar(45),
        in D22SigamaV varchar(45),
        in D22kV varchar(45),
        in D22bV varchar(45),
        in D22AV varchar(45),
        in D22BBV varchar(45),
        in D22CV varchar(45),
        in D22S00V varchar(45),
        in D22S01V varchar(45),
        in D22S02V varchar(45),
        in D22S03V varchar(45),
        in D22S04V varchar(45),
        in D22S05V varchar(45),
        in D22S06V varchar(45),
        in D22S07V varchar(45),
        in D22S08V varchar(45),
        in D22S09V varchar(45),
        in D22S10V varchar(45),
        in D22S11V varchar(45),
        in D22S12V varchar(45),
        in D22S13V varchar(45),
        in D22S14V varchar(45),
        in D22S15V varchar(45),
        in D22S16V varchar(45),
        in D22S17V varchar(45),
        in D22S18V varchar(45),
        in D22S19V varchar(45),
        in D22S20V varchar(45),
        in D22S21V varchar(45),
        in D22SS0102V varchar(45),
        in D22SS0304V varchar(45),
        in D22SS0506V varchar(45),
        in D22SS0708V varchar(45),
        in D22SS0910V varchar(45),
        in D22SS1112V varchar(45),
        in D22SS1314V varchar(45),
        in D22SS1516V varchar(45),
        in D22SS1718V varchar(45),
        in D22SS1920V varchar(45),
        in yearV varchar(45),
        in monthV varchar(45),
        in dayV varchar(45),
        in hourV varchar(45),
        in typeV varchar(45)
)
BEGIN
INSERT INTO `psldb`.`psl_mfdistribute22`
(`D22Avg`,
`D22Sigama`,
`D22k`,
`D22b`,
`D22A`,
`D22BB`,
`D22C`,
`D22S00`,
`D22S01`,
`D22S02`,
`D22S03`,
`D22S04`,
`D22S05`,
`D22S06`,
`D22S07`,
`D22S08`,
`D22S09`,
`D22S10`,
`D22S11`,
`D22S12`,
`D22S13`,
`D22S14`,
`D22S15`,
`D22S16`,
`D22S17`,
`D22S18`,
`D22S19`,
`D22S20`,
`D22S21`,
`D22SS0102`,
`D22SS0304`,
`D22SS0506`,
`D22SS0708`,
`D22SS0910`,
`D22SS1112`,
`D22SS1314`,
`D22SS1516`,
`D22SS1718`,
`D22SS1920`,
`yearvalue`,
`monthvalue`,
`dayvalue`,
`hourvalue`,
`tagId`)
VALUES
(D22AvgV,
        D22SigamaV,
        D22kV,
        D22bV,
        D22AV,
        D22BBV,
        D22CV,
        D22S00V,
        D22S01V,
        D22S02V,
        D22S03V,
        D22S04V,
        D22S05V,
        D22S06V,
        D22S07V,
        D22S08V,
        D22S09V,
        D22S10V,
        D22S11V,
        D22S12V,
        D22S13V,
        D22S14V,
        D22S15V,
        D22S16V,
        D22S17V,
        D22S18V,
        D22S19V,
        D22S20V,
        D22S21V,
        D22SS0102V,
        D22SS0304V,
        D22SS0506V,
        D22SS0708V,
        D22SS0910V,
        D22SS1112V,
        D22SS1314V,
        D22SS1516V,
        D22SS1718V,
        D22SS1920V,
        yearV,
        monthV,
        dayV,
        hourV,
        typeV);
        SELECT SCOPE_IDENTITY() as `lastid`;

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertMMultiCal`(
    in MultiCalSumV varchar(45),
    in MultiCalAbsSumV varchar(45),
    in MultiCalMulV varchar(45),
    in MultiCalAbsMulV varchar(45),
    in MultiCalAvgV varchar(45),
    in MultiCalAbsAvgV varchar(45)
)
BEGIN
    INSERT INTO `psldb`.`psl_mmultical`
(`MultiCalSum`,
`MultiCalAbsSum`,
`MultiCalMul`,
`MultiCalAbsMul`,
`MultiCalAvg`,
`MultiCalAbsAvg`)
VALUES
(MultiCalSumV,
MultiCalAbsSumV,
MultiCalMulV,
MultiCalAbsMulV,
MultiCalAvgV,
MultiCalAbsAvgV);

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertMMultiPV`(
     in MultiPVMin text,
        in MultiPVMinP text,
        in MultiPVAvg text,
        in MultiPVAvgP text,
        in MultiPVMax text,
        in MultiPVMaxP text,
        in MultiPVSum text,
        in MultiPVSumABS text,
        in MultiPVStdev text,
        in MultiPVDmax text,
        in MultiPVDmaxDN text,
        in MultiPVDmaxR text,
        in MultiPVTop text,
        in MultiPVTopP text,
        in MultiPVDown text,
        in MultiPVDownP text,
        in MultiPVTurnN text,
        in MultiPVHHN text,
        in MultiPVHHR text,
        in MultiPVHN text,
        in MultiPVHR text,
        in MultiPVRRPN text,
        in MultiPVRRPNR text,
        in MultiPVHL text,
        in MultiPVHLR text,
        in MultiPVLN text,
        in MultiPVLR text,
        in MultiPVLLN text,
        in MultiPVLLR text,
        in MultiPVMedian text,
        in MultiPVLinek text,
        in MultiPVLineb text,
        in MultiPVLineR text,
        in MultiPVQuada text,
        in MultiPVQuadb text,
        in MultiPVQuadc text,
        in MultiPVQuadR text,
        in MultiPVPVOrd text,
        in MultiPVPVAbsOrd text
)
BEGIN
    INSERT INTO `psldb`.`psl_mmultipv`
(`MultiPVMin`,
`MultiPVMinP`,
`MultiPVAvg`,
`MultiPVAvgP`,
`MultiPVMax`,
`MultiPVMaxP`,
`MultiPVSum`,
`MultiPVSumABS`,
`MultiPVStdev`,
`MultiPVDmax`,
`MultiPVDmaxDN`,
`MultiPVDmaxR`,
`MultiPVTop`,
`MultiPVTopP`,
`MultiPVDown`,
`MultiPVDownP`,
`MultiPVTurnN`,
`MultiPVHHN`,
`MultiPVHHR`,
`MultiPVHN`,
`MultiPVHR`,
`MultiPVRRPN`,
`MultiPVRRPNR`,
`MultiPVHL`,
`MultiPVHLR`,
`MultiPVLN`,
`MultiPVLR`,
`MultiPVLLN`,
`MultiPVLLR`,
`MultiPVMedian`,
`MultiPVLinek`,
`MultiPVLineb`,
`MultiPVLineR`,
`MultiPVQuada`,
`MultiPVQuadb`,
`MultiPVQuadc`,
`MultiPVQuadR`,
`MultiPVPVOrd`,
`MultiPVPVAbsOrd`)
VALUES
(
MultiPVMinV,
MultiPVMinPV,
MultiPVAvgV,
MultiPVAvgPV,
MultiPVMaxV,
MultiPVMaxPV,
MultiPVSumV,
MultiPVSumABSV,
MultiPVStdevV,
MultiPVDmaxV,
MultiPVDmaxDNV,
MultiPVDmaxRV,
MultiPVTopV,
MultiPVTopPV,
MultiPVDownV,
MultiPVDownPV,
MultiPVTurnNV,
MultiPVHHNV,
MultiPVHHRV,
MultiPVHNV,
MultiPVHRV,
MultiPVRRPNV,
MultiPVRRPNRV,
MultiPVHLV,
MultiPVHLRV,
MultiPVLNV,
MultiPVLRV,
MultiPVLLNV,
MultiPVLLRV,
MultiPVMedianV,
MultiPVLinekV,
MultiPVLinebV,
MultiPVLineRV,
MultiPVQuadaV,
MultiPVQuadbV,
MultiPVQuadcV,
MultiPVQuadRV,
MultiPVPVOrdV,
MultiPVPVAbsOrdV
);

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertMMultiPVAvgDistance`(
    in MultiPVAvgDistanceMinV varchar(45),
    in MultiPVAvgDistanceMinTimeV varchar(45),
    in MultiPVAvgDistanceMaxV varchar(45),
    in MultiPVAvgDistanceMaxTimeV varchar(45),
    in MultiPVAvgDistanceAvgV varchar(45),
    in MultiPVAvgDistanceStdevV varchar(45),
    in MultiPVAvgDistanceLTV varchar(45),
    in MultiPVAvgDistanceLTRV varchar(45),
    in MultiPVAvgDistanceHTV varchar(45),
    in MultiPVAvgDistanceHTRV varchar(45)
)
BEGIN
    INSERT INTO `psldb`.`psl_mmultipvavgdistance`
(`MultiPVAvgDistanceMin`,
`MultiPVAvgDistanceMinTime`,
`MultiPVAvgDistanceMax`,
`MultiPVAvgDistanceMaxTime`,
`MultiPVAvgDistanceAvg`,
`MultiPVAvgDistanceStdev`,
`MultiPVAvgDistanceLT`,
`MultiPVAvgDistanceLTR`,
`MultiPVAvgDistanceHT`,
`MultiPVAvgDistanceHTR`)
VALUES
(MultiPVAvgDistanceMinV,
MultiPVAvgDistanceMinTimeV,
MultiPVAvgDistanceMaxV,
MultiPVAvgDistanceMaxTimeV,
MultiPVAvgDistanceAvgV,
MultiPVAvgDistanceStdevV,
MultiPVAvgDistanceLTV,
MultiPVAvgDistanceLTRV,
MultiPVAvgDistanceHTV,
MultiPVAvgDistanceHTRV);

SELECT SCOPE_IDENTITY() as `lastid`;
END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertMMultiPVAvgDistanceDetail`(
    in valueDateV varchar(45),
    in valueAmountV varchar(45),
    in parentId int
)
BEGIN
    INSERT INTO `psldb`.`psl_mmultipvavgdistance_detail`
(`pid`,
`valueDate`,
`valueAmount`)
VALUES
(parentId,
valueDateV,
valueAmountV);

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertMPVBase`(
    in PVBMinV varchar(45),
    in PVBMinTimeV varchar(45),
    in PVBAvgV varchar(45),
    in PVBMaxV varchar(45),
    in PVBMaxTimeV varchar(45),
    in PVBDMaxV varchar(45),
    in PVBSumV varchar(45),
    in PVBSumkbV varchar(45),
    in PVBLinekV varchar(45),
    in PVBLinebV varchar(45),
    in PVBSumPNRV varchar(45),
    in PVBAbsSumV varchar(45),
    in PVBStdevV varchar(45),
    in PVBVolatilityV varchar(45),
    in PVBSDMaxV varchar(45),
    in PVBSDMaxRV varchar(45),
    in PVBDN1NumV varchar(45),
    in PVBDN2NumV varchar(45),
    in PVBDN3NumV varchar(45),
    in PVBTNumV varchar(45),
    in PVBVMaxV varchar(45),
    in PVBVMinV varchar(45),
    in PVBVAvgV varchar(45),
    in PVBStbTRV varchar(45),
    in PVBNoStbTRV varchar(45),
    in PVBStbTSLV varchar(45),
    in PVBStbTSLRV varchar(45),
    in PVBNoStbTSLV varchar(45),
    in PVBNoStbTSLRV varchar(45),
    in PVBUpTSLV varchar(45),
    in PVBUpTSLRV varchar(45),
    in PVBDownTSLV varchar(45),
    in PVBDownTSLRV varchar(45),
    in PVBPNumV varchar(45),
    in PVBQltRV varchar(45),
    in PVBQaV varchar(45),
    in PVBQbV varchar(45),
    in PVBQcV varchar(45),
    in PVBStbTSLPVV varchar(45),
    in typeV varchar(45),
    in yearV varchar(45),
    in monthV varchar(45),
    in dayV varchar(45),
    in hourV varchar(45)
)
BEGIN
    INSERT INTO psldb.psl_mpvbase
(`PVBMin`,
`PVBMinTime`,
`PVBAvg`,
`PVBMax`,
`PVBMaxTime`,
`PVBDMax`,
`PVBSum`,
`PVBSumkb`,
`PVBLinek`,
`PVBLineb`,
`PVBSumPNR`,
`PVBAbsSum`,
`PVBStdev`,
`PVBVolatility`,
`PVBSDMax`,
`PVBSDMaxR`,
`PVBDN1Num`,
`PVBDN2Num`,
`PVBDN3Num`,
`PVBTNum`,
`PVBVMax`,
`PVBVMin`,
`PVBVAvg`,
`PVBStbTR`,
`PVBNoStbTR`,
`PVBStbTSL`,
`PVBStbTSLR`,
`PVBNoStbTSL`,
`PVBNoStbTSLR`,
`PVBUpTSL`,
`PVBUpTSLR`,
`PVBDownTSL`,
`PVBDownTSLR`,
`PVBPNum`,
`PVBQltR`,
`PVBQa`,
`PVBQb`,
`PVBQc`,
`PVBStbTSLPV`,
`yearvalue`,
`monthvalue`,
`dayvalue`,
`hourvalue`,
`tagId`)
VALUES
(PVBMinV,
PVBMinTimeV,
PVBAvgV,
PVBMaxV,
PVBMaxTimeV,
PVBDMaxV,
PVBSumV,
PVBSumkbV,
PVBLinekV,
PVBLinebV,
PVBSumPNRV,
PVBAbsSumV,
PVBStdevV,
PVBVolatilityV,
PVBSDMaxV,
PVBSDMaxRV,
PVBDN1NumV,
PVBDN2NumV,
PVBDN3NumV,
PVBTNumV,
PVBVMaxV,
PVBVMinV,
PVBVAvgV,
PVBStbTRV,
PVBNoStbTRV,
PVBStbTSLV,
PVBStbTSLRV,
PVBNoStbTSLV,
PVBNoStbTSLRV,
PVBUpTSLV,
PVBUpTSLRV,
PVBDownTSLV,
PVBDownTSLRV,
PVBPNumV,
PVBQltRV,
PVBQaV,
PVBQbV,
PVBQcV,
PVBStbTSLPVV,
yearV,
monthV,
dayV,
hourV,
typeV);
SELECT SCOPE_IDENTITY() as `lastid`;
END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertMPVBaseMulti`(
     in PVBSymbolMinV text,
        in PVBSymbolMaxV text,
        in PVBSymbolAvgV text,
        in PVBSymbolDMaxV text,
        in PVBSymbolStdevV text,
        in PVBSymbolLinekV text,
        in PVBSymbolLinebV text,
        in PVBSymbolQaV text,
        in PVBSymbolQbV text,
        in PVBSymbolQcV text,
        in PVBSymbol_PVBMin_OrdV text,
        in PVBSymbol_PVBMinTime_OrdV text,
        in PVBSymbol_PVBAvg_OrdV text,
        in PVBSymbol_PVBMax_OrdV text,
        in PVBSymbol_PVBMaxTime_OrdV text,
        in PVBSymbol_PVBDMax_OrdV text,
        in PVBSymbol_PVBSum_OrdV text,
        in PVBSymbol_PVBSumkb_OrdV text,
        in PVBSymbol_PVBLinek_OrdV text,
        in PVBSymbol_PVBLineb_OrdV text,
        in PVBSymbol_PVBSumPNR_OrdV text,
        in PVBSymbol_PVBAbsSum_OrdV text,
        in PVBSymbol_PVBStdev_OrdV text,
        in PVBSymbol_PVBVolatility_OrdV text,
        in PVBSymbol_PVBSDMax_OrdV text,
        in PVBSymbol_PVBSDMaxR_OrdV text,
        in PVBSymbol_PVBDN1Num_OrdV text,
        in PVBSymbol_PVBDN2Num_OrdV text,
        in PVBSymbol_PVBDN3Num_OrdV text,
        in PVBSymbol_PVBTNum_OrdV text,
        in PVBSymbol_PVBVMax_OrdV text,
        in PVBSymbol_PVBVMin_OrdV text,
        in PVBSymbol_PVBVAvg_OrdV text,
        in PVBSymbol_PVBStbTR_OrdV text,
        in PVBSymbol_PVBNoStbTR_OrdV text,
        in PVBSymbol_PVBStbTSL_OrdV text,
        in PVBSymbol_PVBStbTSLR_OrdV text,
        in PVBSymbol_PVBNoStbTSL_OrdV text,
        in PVBSymbol_PVBNoStbTSLR_OrdV text,
        in PVBSymbol_PVBUpTSL_OrdV text,
        in PVBSymbol_PVBUpTSLR_OrdV text,
        in PVBSymbol_PVBDownTSL_OrdV text,
        in PVBSymbol_PVBDownTSLR_OrdV text,
        in PVBSymbol_PVBPNum_OrdV text,
        in PVBSymbol_PVBQltR_OrdV text,
        in PVBSymbol_PVBStatus_OrdV text,
        in PVBSymbol_PVBQa_OrdV text,
        in PVBSymbol_PVBQb_OrdV text,
        in PVBSymbol_PVBQc_OrdV text,
        in PVBSymbol_PVBStbTSLPV_OrdV text
)
BEGIN
    INSERT INTO `psldb`.`psl_mpvbasemulti`
(`PVBSymbolMin`,
`PVBSymbolMax`,
`PVBSymbolAvg`,
`PVBSymbolDMax`,
`PVBSymbolStdev`,
`PVBSymbolLinek`,
`PVBSymbolLineb`,
`PVBSymbolQa`,
`PVBSymbolQb`,
`PVBSymbolQc`,
`PVBSymbol_PVBMin_Ord`,
`PVBSymbol_PVBMinTime_Ord`,
`PVBSymbol_PVBAvg_Ord`,
`PVBSymbol_PVBMax_Ord`,
`PVBSymbol_PVBMaxTime_Ord`,
`PVBSymbol_PVBDMax_Ord`,
`PVBSymbol_PVBSum_Ord`,
`PVBSymbol_PVBSumkb_Ord`,
`PVBSymbol_PVBLinek_Ord`,
`PVBSymbol_PVBLineb_Ord`,
`PVBSymbol_PVBSumPNR_Ord`,
`PVBSymbol_PVBAbsSum_Ord`,
`PVBSymbol_PVBStdev_Ord`,
`PVBSymbol_PVBVolatility_Ord`,
`PVBSymbol_PVBSDMax_Ord`,
`PVBSymbol_PVBSDMaxR_Ord`,
`PVBSymbol_PVBDN1Num_Ord`,
`PVBSymbol_PVBDN2Num_Ord`,
`PVBSymbol_PVBDN3Num_Ord`,
`PVBSymbol_PVBTNum_Ord`,
`PVBSymbol_PVBVMax_Ord`,
`PVBSymbol_PVBVMin_Ord`,
`PVBSymbol_PVBVAvg_Ord`,
`PVBSymbol_PVBStbTR_Ord`,
`PVBSymbol_PVBNoStbTR_Ord`,
`PVBSymbol_PVBStbTSL_Ord`,
`PVBSymbol_PVBStbTSLR_Ord`,
`PVBSymbol_PVBNoStbTSL_Ord`,
`PVBSymbol_PVBNoStbTSLR_Ord`,
`PVBSymbol_PVBUpTSL_Ord`,
`PVBSymbol_PVBUpTSLR_Ord`,
`PVBSymbol_PVBDownTSL_Ord`,
`PVBSymbol_PVBDownTSLR_Ord`,
`PVBSymbol_PVBPNum_Ord`,
`PVBSymbol_PVBQltR_Ord`,
`PVBSymbol_PVBStatus_Ord`,
`PVBSymbol_PVBQa_Ord`,
`PVBSymbol_PVBQb_Ord`,
`PVBSymbol_PVBQc_Ord`,
`PVBSymbol_PVBStbTSLPV_Ord`)
VALUES
(PVBSymbolMinV,
PVBSymbolMaxV,
PVBSymbolAvgV,
PVBSymbolDMaxV,
PVBSymbolStdevV,
PVBSymbolLinekV,
PVBSymbolLinebV,
PVBSymbolQaV,
PVBSymbolQbV,
PVBSymbolQcV,
PVBSymbol_PVBMin_OrdV,
PVBSymbol_PVBMinTime_OrdV,
PVBSymbol_PVBAvg_OrdV,
PVBSymbol_PVBMax_OrdV,
PVBSymbol_PVBMaxTime_OrdV,
PVBSymbol_PVBDMax_OrdV,
PVBSymbol_PVBSum_OrdV,
PVBSymbol_PVBSumkb_OrdV,
PVBSymbol_PVBLinek_OrdV,
PVBSymbol_PVBLineb_OrdV,
PVBSymbol_PVBSumPNR_OrdV,
PVBSymbol_PVBAbsSum_OrdV,
PVBSymbol_PVBStdev_OrdV,
PVBSymbol_PVBVolatility_OrdV,
PVBSymbol_PVBSDMax_OrdV,
PVBSymbol_PVBSDMaxR_OrdV,
PVBSymbol_PVBDN1Num_OrdV,
PVBSymbol_PVBDN2Num_OrdV,
PVBSymbol_PVBDN3Num_OrdV,
PVBSymbol_PVBTNum_OrdV,
PVBSymbol_PVBVMax_OrdV,
PVBSymbol_PVBVMin_OrdV,
PVBSymbol_PVBVAvg_OrdV,
PVBSymbol_PVBStbTR_OrdV,
PVBSymbol_PVBNoStbTR_OrdV,
PVBSymbol_PVBStbTSL_OrdV,
PVBSymbol_PVBStbTSLR_OrdV,
PVBSymbol_PVBNoStbTSL_OrdV,
PVBSymbol_PVBNoStbTSLR_OrdV,
PVBSymbol_PVBUpTSL_OrdV,
PVBSymbol_PVBUpTSLR_OrdV,
PVBSymbol_PVBDownTSL_OrdV,
PVBSymbol_PVBDownTSLR_OrdV,
PVBSymbol_PVBPNum_OrdV,
PVBSymbol_PVBQltR_OrdV,
PVBSymbol_PVBStatus_OrdV,
PVBSymbol_PVBQa_OrdV,
PVBSymbol_PVBQb_OrdV,
PVBSymbol_PVBQc_OrdV,
PVBSymbol_PVBStbTSLPV_OrdV
);

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertMPVOverRangeEva`(
    in OverHRangeV varchar(45),
    in OverHFreV varchar(45),
    in OverLRangeV varchar(45),
    in OverLFreV varchar(45),
    in yearV varchar(45),
    in monthV varchar(45),
    in dayV varchar(45),
    in hourV varchar(45),
    in typeV varchar(45)
)
BEGIN
    INSERT INTO `psldb`.`psl_mpvoverrangeeva`
(`OverHRange`,
`OverHFre`,
`OverLRange`,
`OverLFre`,
`yearvalue`,
`monthvalue`,
`dayvalue`,
`hourvalue`,
`tagId`)
VALUES
(OverHRangeV,
OverHFreV,
OverLRangeV,
OverLFreV,
yearV,
monthV,
dayV,
hourV,
typeV);

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertMPVScoreEva`(
    in SftScoreMinV varchar(45),
    in SftScoreMinTV varchar(45),
    in SftScoreMaxV varchar(45),
    in SftScoreMaxTV varchar(45),
    in SftScoreAvgV varchar(45),
    in SftScoreAvgPV varchar(45),
    in SftScoreTotalV varchar(45),
    in SftScoreTotalPV varchar(45),
    in SftScoreHighTV varchar(45),
    in SftScoreHighTRV varchar(45),
    in SftScoreHighSTV varchar(45),
    in SftScoreLowTV varchar(45),
    in SftScoreLowTRV varchar(45),
    in SftScoreLowSTV varchar(45),
    in SftScoreEvaV varchar(45),
    in StartTimeV varchar(45),
    in EndTimeV varchar(45),
    in totalHourV varchar(45),
    in yearV varchar(45),
    in monthV varchar(45),
    in dayV varchar(45),
    in hourV varchar(45),
    in typeV varchar(45)
)
BEGIN
    INSERT INTO `psldb`.`psl_mpvscoreeva`
(`SftScoreMin`,
`SftScoreMinT`,
`SftScoreMax`,
`SftScoreMaxT`,
`SftScoreAvg`,
`SftScoreAvgP`,
`SftScoreTotal`,
`SftScoreTotalP`,
`SftScoreHighT`,
`SftScoreHighTR`,
`SftScoreHighST`,
`SftScoreLowT`,
`SftScoreLowTR`,
`SftScoreLowST`,
`SftScoreEva`,
`StartTime`,
`totalHour`,
`yearvalue`,
`monthvalue`,
`dayvalue`,
`hourvalue`,
`tagId`)
VALUES
(SftScoreMinV,
SftScoreMinTV,
SftScoreMaxV,
SftScoreMaxTV,
SftScoreAvgV,
SftScoreAvgPV,
SftScoreTotalV,
SftScoreTotalPV,
SftScoreHighTV,
SftScoreHighTRV,
SftScoreHighSTV,
SftScoreLowTV,
SftScoreLowTRV,
SftScoreLowSTV,
SftScoreEvaV,
StartTimeV,
totalHourV,
yearvalueV,
monthvalueV,
dayvalueV,
hourvalueV,
typeV);
SELECT SCOPE_IDENTITY() as `lastid`;
END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertMPVTypeRangeDetail`(
     in PVDAvgV varchar(45),
     in PVDMaxV varchar(45),
     in PVDMinV varchar(45),
     in PVMAvgV varchar(45),
     in PVMMaxV varchar(45),
     in PVMMinV varchar(45),
     in pid int
)
BEGIN
    INSERT INTO `psldb`.`psl_mpvtyperange_detail`
(`parentId`,
`PVDAvg`,
`PVDMax`,
`PVDMin`,
`PVMAvg`,
`PVMMax`,
`PVMMin`)
VALUES
(pid,
PVDAvgV,
PVDMaxV,
PVDMinV,
PVMAvgV,
PVMMaxV,
PVMMinV);


END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertMPVTypRange`(
    in PVDAreaV varchar(45),
                    in PVMAreaV varchar(45),
                    in PVDAvgClsDayV varchar(45),
                    in PVDAvgFarDayV varchar(45),
                    in PVDMaxClsDayV varchar(45),
                    in PVDMaxFarDayV varchar(45),
                    in PVDMinClsDayV varchar(45),
                    in PVDMinFarDayV varchar(45),
                    in PVMAvgClsMonthV varchar(45),
                    in PVMAvgFarMonthV varchar(45),
                    in PVMMaxClsMonthV varchar(45),
                    in PVMMaxFarMonthV varchar(45),
                    in PVMMinClsMonthV varchar(45),
                    in PVMMinFarMonthV varchar(45),
                    in PVDAvgClsDistV varchar(45),
                    in PVDAvgFarDistV varchar(45),
                    in PVDMaxClsDistV varchar(45),
                    in PVDMaxFarDistV varchar(45),
                    in PVDMinClsDistV varchar(45),
                    in PVDMinFarDistV varchar(45),
                    in PVMAvgClsDistV varchar(45),
                    in PVMAvgFarDistV varchar(45),
                    in PVMMaxClsDistV varchar(45),
                    in PVMMaxFarDistV varchar(45),
                    in PVMMinClsDistV varchar(45),
                    in PVMMinFarDistV varchar(45),
                    in PVDAvgDistStdevV varchar(45),
                    in PVMAvgDistStdevV varchar(45),
                    in PVDAvgDistLinekV varchar(45),
                    in PVDAvgDistLinebV varchar(45),
                    in PVMAvgDistLinekV varchar(45),
                    in PVMAvgDistLinebV varchar(45),
                    in yearV varchar(45),
                    in monthV varchar(45),
                    in dayV varchar(45),
                    in hourV varchar(45),
                    in typeV varchar(45)
)
BEGIN
    INSERT INTO `psldb`.`psl_mpvtyprange`
(`yearvalue`,
`monthvalue`,
`dayvalue`,
`hourvalue`,
`tagid`,
`PVDArea`,
`PVMArea`,
`PVDAvgClsDay`,
`PVDAvgFarDay`,
`PVDMaxClsDay`,
`PVDMaxFarDay`,
`PVDMinClsDay`,
`PVDMinFarDay`,
`PVMAvgClsMonth`,
`PVMAvgFarMonth`,
`PVMMaxClsMonth`,
`PVMMaxFarMonth`,
`PVMMinClsMonth`,
`PVMMinFarMonth`,
`PVDAvgClsDist`,
`PVDAvgFarDist`,
`PVDMaxClsDist`,
`PVDMaxFarDist`,
`PVDMinClsDist`,
`PVDMinFarDist`,
`PVMAvgClsDist`,
`PVMAvgFarDist`,
`PVMMaxClsDist`,
`PVMMaxFarDist`,
`PVMMinClsDist`,
`PVMMinFarDist`,
`PVDAvgDistStdev`,
`PVMAvgDistStdev`,
`PVDAvgDistLinek`,
`PVDAvgDistLineb`,
`PVMAvgDistLinek`,
`PVMAvgDistLineb`)
VALUES
(yearV,
monthV,
dayV,
hourV,
typeV,
PVDAreaV,
PVMAreaV,
PVDAvgClsDayV,
PVDAvgFarDayV,
PVDMaxClsDayV,
PVDMaxFarDayV,
PVDMinClsDayV,
PVDMinFarDayV,
PVMAvgClsMonthV,
PVMAvgFarMonthV,
PVMMaxClsMonthV,
PVMMaxFarMonthV,
PVMMinClsMonthV,
PVMMinFarMonthV,
PVDAvgClsDistV,
PVDAvgFarDistV,
PVDMaxClsDistV,
PVDMaxFarDistV,
PVDMinClsDistV,
PVDMinFarDistV,
PVMAvgClsDistV,
PVMAvgFarDistV,
PVMMaxClsDistV,
PVMMaxFarDistV,
PVMMinClsDistV,
PVMMinFarDistV,
PVDAvgDistStdevV,
PVMAvgDistStdevV,
PVDAvgDistLinekV,
PVDAvgDistLinebV,
PVMAvgDistLinekV,
PVMAvgDistLinebV);
SELECT SCOPE_IDENTITY() as `lastid`;

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertMPVUTNV`(
    in yvalue varchar(45),
    in mvalue varchar(45),
    in dvalue varchar(45),
    in hvalue varchar(45),
    in tid varchar(45)
)
BEGIN
    INSERT INTO `psldb`.`psl_mpvutnv`
(`yearvalue`,
`monthvalue`,
`dayvalue`,
`hourvalue`,
`tagId`)
VALUES
(yvalue,
mvalue,
dvalue,
hvalue,
tid);
SELECT LAST_INSERT_ID() as pid;
END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertMPVUTNVDetail`(
    in parentid int,
    in vType varchar(50),
    in MY varchar(50),
    in MM varchar(50),
    in MD varchar(50),
    in MH varchar(50)
)
BEGIN
    INSERT INTO `psldb`.`psl_mpvutnv_detail`
(`pid`,
`valueType`,
`MPVUTNVH`,
`MPVUTNVD`,
`MPVUTNVM`,
`MPVUTNVY`)
VALUES
(parentid,
vType,
MY,
MM,
MD,
MH);

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertTimeValue`(
    in sDate varchar(45),
    in eDate varchar(45),
    in aid int,
    in pid int,
    in cid int
)
BEGIN
    INSERT INTO `psldb`.`psl_timedata`
(`AlgorithmId`,
`parentid`,
`columnid`,
`startDate`,
`endDate`)
VALUES
(aid,
pid,
cid,
sDate,
eDate);

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateMDevLimit`(
        in pid int,
        in DevHHNV varchar(45),
        in DevHHTV varchar(45),
        in DevHHRV varchar(45),
        in DevHHTMaxV varchar(45),
        in DevHHAV varchar(45),
        in DevHHETV varchar(45),
        in DevHNV varchar(45),
        in DevHTV varchar(45),
        in DevHRV varchar(45),
        in DevHTMaxV varchar(45),
        in DevHAV varchar(45),
        in DevHETV varchar(45),
        in DevRPNV varchar(45),
        in DevRPTV varchar(45),
        in DevRPRV varchar(45),
        in DevRPTMaxV varchar(45),
        in DevRPAV varchar(45),
        in DevRPETV varchar(45),
        in Dev0PNV varchar(45),
        in Dev0PTV varchar(45),
        in Dev0PRV varchar(45),
        in Dev0PTMaxV varchar(45),
        in Dev0PAV varchar(45),
        in Dev0PETV varchar(45),
        in Dev0NNV varchar(45),
        in Dev0NTV varchar(45),
        in Dev0NRV varchar(45),
        in Dev0NTMaxV varchar(45),
        in Dev0NAV varchar(45),
        in Dev0NETV varchar(45),
        in DevRNNV varchar(45),
        in DevRNTV varchar(45),
        in DevRNRV varchar(45),
        in DevRNTMaxV varchar(45),
        in DevRNAV varchar(45),
        in DevRNETV varchar(45),
        in DevLNV varchar(45),
        in DevLTV varchar(45),
        in DevLRV varchar(45),
        in DevLTMaxV varchar(45),
        in DevLAV varchar(45),
        in DevLETV varchar(45),
        in DevLLNV varchar(45),
        in DevLLTV varchar(45),
        in DevLLRV varchar(45),
        in DevLLTMaxV varchar(45),
        in DevLLAV varchar(45),
        in DevLLETV varchar(45),
        in Dev0HTV varchar(45),
        in Dev0HTRV varchar(45),
        in Dev0HHTV varchar(45),
        in Dev0HHTRV varchar(45),
        in Dev0LV varchar(45),
        in Dev0LRV varchar(45),
        in Dev0LLTV varchar(45),
        in Dev0LLTRV varchar(45),
        in DevHHLLTV varchar(45),
        in DevHHLLTRV varchar(45),
        in DevHLHHLLTV varchar(45),
        in DevHLHHLLRV varchar(45),
        in DevRPRMHLTV varchar(45),
        in DevRPRMHLTRV varchar(45),
        in Dev0RPRMTV varchar(45),
        in Dev0RPRMTRV varchar(45),
        in Dev0RPRMTMaxV varchar(45),
        in DevHLTV varchar(45),
        in DevHLTRV varchar(45),
        in DevHLTMaxV varchar(45),
        in DevPTV varchar(45),
        in DevPTRV varchar(45),
        in DevPTRTMaxV varchar(45),
        in DevNTV varchar(45),
        in DevNTRV varchar(45),
        in DevNTRTMaxV varchar(45)
)
BEGIN
    UPDATE `psldb`.`psl_mdevlimit`
SET
`DevHHN` = DevHHNV,
`DevHHT` = DevHHTV,
`DevHHR` = DevHHRV,
`DevHHTMax` = DevHHTMaxV,
`DevHHA` = DevHHAV,
`DevHHET` = DevHHETV,
`DevHN` = DevHNV,
`DevHT` = DevHTV,
`DevHR` = DevHRV,
`DevHTMax` = DevHTMaxV,
`DevHA` = DevHAV,
`DevHET` = DevHETV,
`DevRPN` = DevRPNV,
`DevRPT` = DevRPTV,
`DevRPR` = DevRPRV,
`DevRPTMax` = DevRPTMaxV,
`DevRPA` = DevRPAV,
`DevRPET` = DevRPETV,
`Dev0PN` = Dev0PNV,
`Dev0PT` = Dev0PTV,
`Dev0PR` = Dev0PRV,
`Dev0PTMax` = Dev0PTMaxV,
`Dev0PA` = Dev0PAV,
`Dev0PET` = Dev0PETV,
`Dev0NN` = Dev0NNV,
`Dev0NT` = Dev0NTV,
`Dev0NR` = Dev0NRV,
`Dev0NTMax` = Dev0NTMaxV,
`Dev0NA` = Dev0NAV,
`Dev0NET` = Dev0NETV,
`DevRNN` = DevRNNV,
`DevRNT` = DevRNTV,
`DevRNR` = DevRNRV,
`DevRNTMax` = DevRNTMaxV,
`DevRNA` = DevRNAV,
`DevRNET` = DevRNETV,
`DevLN` = DevLNV,
`DevLT` = DevLTV,
`DevLR` = DevLRV,
`DevLTMax` = DevLTMaxV,
`DevLA` = DevLAV,
`DevLET` = DevLETV,
`DevLLN` = DevLLNV,
`DevLLT` = DevLLTV,
`DevLLR` = DevLLRV,
`DevLLTMax` = DevLLTMaxV,
`DevLLA` = DevLLAV,
`DevLLET` = DevLLETV,
`Dev0HT` = Dev0HTV,
`Dev0HTR` = Dev0HTRV,
`Dev0HHT` = Dev0HHTV,
`Dev0HHTR` = Dev0HHTRV,
`Dev0L` = Dev0LV,
`Dev0LR` = Dev0LRV,
`Dev0LLT` = Dev0LLTV,
`Dev0LLTR` = Dev0LLTRV,
`DevHHLLT` = DevHHLLTV,
`DevHHLLTR` = DevHHLLTRV,
`DevHLHHLLT` = DevHLHHLLTV,
`DevHLHHLLR` = DevHLHHLLRV,
`DevRPRMHLT` = DevRPRMHLTV,
`DevRPRMHLTR` = DevRPRMHLTRV,
`Dev0RPRMT` = Dev0RPRMTV,
`Dev0RPRMTR` = Dev0RPRMTRV,
`Dev0RPRMTMax` = Dev0RPRMTMaxV,
`DevHLT` = DevHLTV,
`DevHLTR` = DevHLTRV,
`DevHLTMax` = DevHLTMaxV,
`DevPT` = DevPTV,
`DevPTR` = DevPTRV,
`DevPTRTMax` = DevPTRTMaxV,
`DevNT` = DevNTV,
`DevNTR` = DevNTRV,
`DevNTRTMax` = DevNTRTMaxV
WHERE `id` = pid;

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateMFDistribute22`(
        in pid int,
        in D22AvgV varchar(45),
        in D22SigamaV varchar(45),
        in D22kV varchar(45),
        in D22bV varchar(45),
        in D22AV varchar(45),
        in D22BBV varchar(45),
        in D22CV varchar(45),
        in D22S00V varchar(45),
        in D22S01V varchar(45),
        in D22S02V varchar(45),
        in D22S03V varchar(45),
        in D22S04V varchar(45),
        in D22S05V varchar(45),
        in D22S06V varchar(45),
        in D22S07V varchar(45),
        in D22S08V varchar(45),
        in D22S09V varchar(45),
        in D22S10V varchar(45),
        in D22S11V varchar(45),
        in D22S12V varchar(45),
        in D22S13V varchar(45),
        in D22S14V varchar(45),
        in D22S15V varchar(45),
        in D22S16V varchar(45),
        in D22S17V varchar(45),
        in D22S18V varchar(45),
        in D22S19V varchar(45),
        in D22S20V varchar(45),
        in D22S21V varchar(45),
        in D22SS0102V varchar(45),
        in D22SS0304V varchar(45),
        in D22SS0506V varchar(45),
        in D22SS0708V varchar(45),
        in D22SS0910V varchar(45),
        in D22SS1112V varchar(45),
        in D22SS1314V varchar(45),
        in D22SS1516V varchar(45),
        in D22SS1718V varchar(45),
        in D22SS1920V varchar(45)
)
BEGIN
UPDATE `psldb`.`psl_mfdistribute22`
SET
`D22Avg` = D22AvgV,
`D22Sigama` = D22SigamaV,
`D22k` = D22kV,
`D22b` = D22bV,
`D22A` = D22AV,
`D22BB` = D22BBV,
`D22C` = D22CV,
`D22S00` = D22S00V,
`D22S01` = D22S01V,
`D22S02` = D22S02V,
`D22S03` = D22S03V,
`D22S04` = D22S04V,
`D22S05` = D22S05V,
`D22S06` = D22S06V,
`D22S07` = D22S07V,
`D22S08` = D22S08V,
`D22S09` = D22S09V,
`D22S10` = D22S10V,
`D22S11` = D22S11V,
`D22S12` = D22S12V,
`D22S13` = D22S13V,
`D22S14` = D22S14V,
`D22S15` = D22S15V,
`D22S16` = D22S16V,
`D22S17` = D22S17V,
`D22S18` = D22S18V,
`D22S19` = D22S19V,
`D22S20` = D22S20V,
`D22S21` = D22S21V,
`D22SS0102` = D22SS0102V,
`D22SS0304` = D22SS0304V,
`D22SS0506` = D22SS0506V,
`D22SS0708` = D22SS0708V,
`D22SS0910` = D22SS0910V,
`D22SS1112` = D22SS1112V,
`D22SS1314` = D22SS1314V,
`D22SS1516` = D22SS1516V,
`D22SS1718` = D22SS1718V,
`D22SS1920` = D22SS1920V
WHERE `id` = pid;

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateMPVBase`(
    in pid int,
    in PVBMinV varchar(45),
    in PVBMinTimeV varchar(45),
    in PVBAvgV varchar(45),
    in PVBMaxV varchar(45),
    in PVBMaxTimeV varchar(45),
    in PVBDMaxV varchar(45),
    in PVBSumV varchar(45),
    in PVBSumkbV varchar(45),
    in PVBLinekV varchar(45),
    in PVBLinebV varchar(45),
    in PVBSumPNRV varchar(45),
    in PVBAbsSumV varchar(45),
    in PVBStdevV varchar(45),
    in PVBVolatilityV varchar(45),
    in PVBSDMaxV varchar(45),
    in PVBSDMaxRV varchar(45),
    in PVBDN1NumV varchar(45),
    in PVBDN2NumV varchar(45),
    in PVBDN3NumV varchar(45),
    in PVBTNumV varchar(45),
    in PVBVMaxV varchar(45),
    in PVBVMinV varchar(45),
    in PVBVAvgV varchar(45),
    in PVBStbTRV varchar(45),
    in PVBNoStbTRV varchar(45),
    in PVBStbTSLV varchar(45),
    in PVBStbTSLRV varchar(45),
    in PVBNoStbTSLV varchar(45),
    in PVBNoStbTSLRV varchar(45),
    in PVBUpTSLV varchar(45),
    in PVBUpTSLRV varchar(45),
    in PVBDownTSLV varchar(45),
    in PVBDownTSLRV varchar(45),
    in PVBPNumV varchar(45),
    in PVBQltRV varchar(45),
    in PVBQaV varchar(45),
    in PVBQbV varchar(45),
    in PVBQcV varchar(45),
    in PVBStbTSLPVV varchar(45)
)
BEGIN
    UPDATE `psldb`.`psl_mpvbase`
    SET
    `PVBMin` = PVBMinV,
    `PVBMinTime` = PVBMinTimeV,
    `PVBAvg` = PVBAvgV,
    `PVBMax` = PVBMaxV,
    `PVBMaxTime` = PVBMaxTimeV,
    `PVBDMax` = PVBDMaxV,
    `PVBSum` = PVBSumV,
    `PVBSumkb` = PVBSumkbV,
    `PVBLinek` = PVBLinekV,
    `PVBLineb` = PVBLinebV,
    `PVBSumPNR` = PVBSumPNRV,
    `PVBAbsSum` = PVBAbsSumV,
    `PVBStdev` = PVBStdevV,
    `PVBVolatility` = PVBVolatilityV,
    `PVBSDMax` = PVBSDMaxV,
    `PVBSDMaxR` = PVBSDMaxRV,
    `PVBDN1Num` = PVBDN1NumV,
    `PVBDN2Num` = PVBDN2NumV,
    `PVBDN3Num` = PVBDN3NumV,
    `PVBTNum` = PVBTNumV,
    `PVBVMax` = PVBVMaxV,
    `PVBVMin` = PVBVMinV,
    `PVBVAvg` = PVBVAvgV,
    `PVBStbTR` = PVBStbTRV,
    `PVBNoStbTR` = PVBNoStbTRV,
    `PVBStbTSL` = PVBStbTSLV,
    `PVBStbTSLR` = PVBStbTSLRV,
    `PVBNoStbTSL` = PVBNoStbTSLV,
    `PVBNoStbTSLR` = PVBNoStbTSLRV,
    `PVBUpTSL` = PVBUpTSLV,
    `PVBUpTSLR` = PVBUpTSLRV,
    `PVBDownTSL` = PVBDownTSLV,
    `PVBDownTSLR` = PVBDownTSLRV,
    `PVBPNum` = PVBPNumV,
    `PVBQltR` = PVBQltRV,
    `PVBQa` = PVBQaV,
    `PVBQb` = PVBQbV,
    `PVBQc` = PVBQcV,
    `PVBStbTSLPV` = PVBStbTSLPVV
    WHERE `id` = pid;

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateMPVOverRangeEva`(
    in pid int,
    in OverHRangeV varchar(45),
    in OverHFreV varchar(45),
    in OverLRangeV varchar(45),
    in OverLFreV varchar(45)
)
BEGIN
    UPDATE `psldb`.`psl_mpvoverrangeeva`
SET
`OverHRange` = OverHRangeV,
`OverHFre` = OverHFreV,
`OverLRange` = OverLRangeV,
`OverLFre` = OverLFreV
WHERE `id` = pid;

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateMPVScoreEva`(
    in pid int,
    in SftScoreMinV varchar(45),
    in SftScoreMinTV varchar(45),
    in SftScoreMaxV varchar(45),
    in SftScoreMaxTV varchar(45),
    in SftScoreAvgV varchar(45),
    in SftScoreAvgPV varchar(45),
    in SftScoreTotalV varchar(45),
    in SftScoreTotalPV varchar(45),
    in SftScoreHighTV varchar(45),
    in SftScoreHighTRV varchar(45),
    in SftScoreHighSTV varchar(45),
    in SftScoreLowTV varchar(45),
    in SftScoreLowTRV varchar(45),
    in SftScoreLowSTV varchar(45),
    in SftScoreEvaV varchar(45),
    in StartTimeV varchar(45),
    in EndTimeV varchar(45),
    in totalHourV varchar(45)
)
BEGIN
    UPDATE `psldb`.`psl_mpvscoreeva`
SET
`SftScoreMin` = SftScoreMinV,
`SftScoreMinT` = SftScoreMinTV,
`SftScoreMax` = SftScoreMaxV,
`SftScoreMaxT` = SftScoreMaxTV,
`SftScoreAvg` = SftScoreAvgV,
`SftScoreAvgP` = SftScoreAvgPV,
`SftScoreTotal` = SftScoreTotalV,
`SftScoreTotalP` = SftScoreTotalPV,
`SftScoreHighT` = SftScoreHighTV,
`SftScoreHighTR` = SftScoreHighTRV,
`SftScoreHighST` = SftScoreHighSTV,
`SftScoreLowT` = SftScoreLowTV,
`SftScoreLowTR` = SftScoreLowTRV,
`SftScoreLowST` = SftScoreLowSTV,
`SftScoreEva` = SftScoreEvaV,
`StartTime` = StartTimeV,
`totalHour` = totalHourV
WHERE `id` = pid;

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertMDeviationS`(
    in spV varchar(45),
    in errV varchar(45),
    in errrateV varchar(45),
    in scoreV varchar(45),
    in wscoreV varchar(45),
    in typeV varchar(45),
    in yearV varchar(45),
    in monthV varchar(45),
    in dayV varchar(45),
    in hourV varchar(45)
)
BEGIN
    INSERT INTO `psldb`.`psl_mdeviations`
(`sp`,
`err`,
`errrate`,
`score`,
`wscore`,
`yearvalue`,
`monthvalue`,
`dayvalue`,
`hourvalue`,
`tagId`)
VALUES
(spV,
errV,
errrateV,
scoreV,
wscoreV,
yearV,
monthV,
dayV,
hourV,
typeV);
END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateMDeviationS`(
    in pid int,
    in spV varchar(45),
    in errV varchar(45),
    in errrateV varchar(45),
    in scoreV varchar(45),
    in wscoreV varchar(45)
)
BEGIN
    UPDATE `psldb`.`psl_mdeviations`
SET
`sp` = spV,
`err` = errV,
`errrate` = errrateV,
`score` = scoreV,
`wscore` = wscoreV
WHERE `id` = pid;

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertMDeviation2DS`(
    in spV varchar(45),
    in errV varchar(45),
    in errrateV varchar(45),
    in scoreV varchar(45),
    in wscoreV varchar(45),
    in typeV varchar(45),
    in yearV varchar(45),
    in monthV varchar(45),
    in dayV varchar(45),
    in hourV varchar(45)
)
BEGIN
    INSERT INTO `psldb`.`psl_mdeviation2ds`
(`sp`,
`err`,
`errrate`,
`score`,
`wscore`,
`yearvalue`,
`monthvalue`,
`dayvalue`,
`hourvalue`,
`tagId`)
VALUES
(spV,
errV,
errrateV,
scoreV,
wscoreV,
yearV,
monthV,
dayV,
hourV,
typeV);
END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateMDeviation2DS`(
    in pid int,
    in spV varchar(45),
    in errV varchar(45),
    in errrateV varchar(45),
    in scoreV varchar(45),
    in wscoreV varchar(45)
)
BEGIN
    UPDATE `psldb`.`psl_mdeviation2ds`
SET
`sp` = spV,
`err` = errV,
`errrate` = errrateV,
`score` = scoreV,
`wscore` = wscoreV
WHERE `id` = pid;

END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `insertMAddMul`(
    in addMulSumV varchar(45),
    in addMulAbsSumV varchar(45),
    in addMulMulV varchar(45),
    in addMulAbsMulV varchar(45),
    in addMulAvgV varchar(45),
    in addMulAbsAvgV varchar(45),
    in typeV varchar(45),
    in yearV varchar(45),
    in monthV varchar(45),
    in dayV varchar(45),
    in hourV varchar(45)
)
BEGIN
    INSERT INTO `psldb`.`psl_maddmul`
(`addmulsum`,
`addmulabssum`,
`addmulmul`,
`addmulabsmul`,
`addmulavg`,
`addmulabsavg`,
`yearvalue`,
`monthvalue`,
`dayvalue`,
`hourvalue`,
`tagId`)
VALUES
(addMulSumV,
addMulAbsSumV,
addMulMulV,
addMulAbsMulV,
addMulAvgV,
addMulAbsAvgV,
yearV,
monthV,
dayV,
hourV,
typeV);
END ;;
sqlSplit
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateMAddMul`(
    in pid int,
    in addMulSumV varchar(45),
    in addMulAbsSumV varchar(45),
    in addMulMulV varchar(45),
    in addMulAbsMulV varchar(45),
    in addMulAvgV varchar(45),
    in addMulAbsAvgV varchar(45)
)
BEGIN
    UPDATE `psldb`.`psl_maddmul`
SET
`addmulsum` = addMulSumV,
`addmulabssum` = addMulAbsSumV,
`addmulmul` = addMulMulV,
`addmulabsmul` = addMulAbsMulV,
`addmulavg` = addMulAvgV,
`addmulabsavg` = addMulAbsAvgV
WHERE `id` = pid;

END ;;